[metadata]
name = "trufflehog"
version = "3.82.2"
description = "TruffleHog - secrets scanner for Git repositories"
vendor = "TruffleHog"
source = "https://github.com/trufflesecurity/trufflehog"
license = "Apache-2.0"
tier = "standard"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/trufflesecurity/trufflehog/releases/download/v3.82.2/trufflehog_3.82.2_linux_amd64.tar.gz"

[runtime]
entrypoint = ["/trufflehog"]
cmd = ["--help"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.description" = "TruffleHog - secret scanner"
"org.opencontainers.image.source" = "https://github.com/trufflesecurity/trufflehog"
"org.opencontainers.image.title" = "trufflehog"
"org.opencontainers.image.vendor" = "trufflesecurity"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"

