[metadata]
name = "rethinkdb"
version = "latest"
description = "Sovereign hardened RethinkDB - real-time NoSQL database"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "rethinkdb/rethinkdb:${VERSION}"

[runtime]
entrypoint = ["/opt/rethinkdb/bin/rethinkdb", "--bind", "all", "--directory", "/data"]

[ports]
expose = [28015, 9101]

[labels]
"org.opencontainers.image.description" = "Sovereign hardened RethinkDB - real-time NoSQL database"
"org.opencontainers.image.title" = "rethinkdb"
"org.opencontainers.image.vendor" = "RethinkDB"
"org.opencontainers.image.version" = "${VERSION}"
"sovereign.base.image" = "wolfi"
"sovereign.constraint.nonroot" = "true"
"sovereign.health.type" = "exec"
"sovereign.image.category" = "database"
"sovereign.image.status" = "functional"
"sovereign.image.tier" = "1"
"sovereign.metrics.native" = "ztunnel"

