[metadata]
name = "skrooge"
version = "2.31.0"
description = "skrooge container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["skrooge"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/skrooge/skrooge"
"org.opencontainers.image.title" = "skrooge"
"org.opencontainers.image.vendor" = "Skrooge"
"org.opencontainers.image.version" = "2.31.0"
"sovereign.base.image" = "wolfi"
"sovereign.constraint.base" = "wolfi"
"sovereign.constraint.nonroot" = "true"
"sovereign.health.type" = "exec"
"sovereign.hft.init-system" = "none"
"sovereign.hft.shutdown-timeout" = "10s"
"sovereign.hft.signal-handling" = "native"
"sovereign.hft.startup-timeout" = "30000ms"
"sovereign.image.category" = "business-finance"
"sovereign.image.status" = "functional"
"sovereign.image.tier" = "2"
"sovereign.metrics.native" = "ztunnel"

