[metadata]
tier = "standard"
name = "openjre"
version = "unknown"
description = "Evergreen hardened OpenJRE 21 (Adoptium) on debian-slim for Java application base"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened OpenJRE 21 (Adoptium) on debian-slim for Java application base"
"org.opencontainers.image.title" = "openjre"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "none"
"evergreen.image.category" = "base"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "standard""evergreen.metrics.native" = "ztunnel"
