[metadata]
name = "vector"
version = "0.39.0"
description = "Vector - high-performance observability data pipeline"
vendor = "Datadog"
source = "https://github.com/vectordotdev/vector"
license = "Apache-2.0"
tier = "2"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/vectordotdev/vector/releases/download/v0.39.0/vector-x86_64-unknown-linux-gnu.tar.gz"

[runtime]
entrypoint = ["/vector"]

[ports]
expose = [9001, 9101]

[labels]
"org.opencontainers.image.title" = "vector"
"org.opencontainers.image.vendor" = "Vector"
"org.opencontainers.image.version" = "0.39.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

