[metadata]
tier = "standard"
name = "r2d2"
version = "0.8.10"
description = "Evergreen hardened R2D2 - generic connection pool wrapper"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/usr/local/bin/r2d2"]

[ports]
expose = [6379, 9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened R2D2 - generic connection pool wrapper"
"org.opencontainers.image.title" = "r2d2"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.image.category" = "database"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

