[metadata]
name = "unbound"
version = "1.20.0"
description = "Unbound - validating, recursive, and caching DNS resolver"
vendor = "NLnet Labs"
source = "https://github.com/NLnetLabs/unbound"
license = "Apache-2.0"
tier = "3"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/unbound/unbound/releases/download/v1.20.0/unbound-1.20.0-linux-amd64.tar.gz"

[runtime]
entrypoint = ["/unbound"]

[ports]
expose = [53, 9101]

[labels]
"org.opencontainers.image.title" = "unbound"
"org.opencontainers.image.vendor" = "NLnet Labs"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

