[metadata]
name = "coredns"
version = "1.12.0"
description = "CoreDNS - DNS server and service discovery for Kubernetes"
vendor = "CNCF"
source = "https://github.com/coredns/coredns"
license = "Apache-2.0"
tier = "1"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/coredns/coredns/releases/download/v1.12.0/coredns-1.12.0-linux-amd64.tar.gz"

[runtime]
entrypoint = ["/coredns"]

[ports]
expose = [53, 9101]

[labels]
"org.opencontainers.image.title" = "coredns"
"org.opencontainers.image.vendor" = "Coredns"
"org.opencontainers.image.version" = "1.12.0"
"sovereign.base.image" = "scratch"
"sovereign.constraint.nonroot" = "true"
"sovereign.constraint.scratch" = "true"
"sovereign.health.type" = "exec"
"sovereign.hft.connection-drain" = "true"
"sovereign.hft.cpu-pins" = "0-1"
"sovereign.hft.cpu-pins-mode" = "exclusive"
"sovereign.hft.deploy-strategy" = "hft-rolling"
"sovereign.hft.init-system" = "none"
"sovereign.hft.pre-stop-delay" = "5s"
"sovereign.hft.pre-stop-hook" = "true"
"sovereign.hft.runtime" = "go"
"sovereign.hft.runtime-hints" = "GOMAXPROCS=<cores>"
"sovereign.hft.sched-policy" = "SCHED_FIFO"
"sovereign.hft.sched-priority" = "65"
"sovereign.hft.shutdown-timeout" = "3s"
"sovereign.hft.signal-handling" = "native"
"sovereign.hft.startup-timeout" = "3000ms"
"sovereign.image.tier" = "1"
"sovereign.metrics.native" = "ztunnel"

