[metadata]
name = "milvus-attu"
version = "2.4.9"
description = "milvus-attu container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "docker.io/zilliz/attu:v2.4.9"

[runtime]
entrypoint = ["/attu"]

[ports]
expose = [3000, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/zilliztech/attu/releases/download/v2.4.9"
"org.opencontainers.image.title" = "milvus-attu"
"org.opencontainers.image.vendor" = "zilliztech/attu"
"org.opencontainers.image.version" = "2.4.9"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"

