[metadata]
tier = "standard"
name = "blocky"
version = "0.29.0"
description = "blocky container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/blocky"]

[ports]
expose = [53, 9101]

[labels]
"org.opencontainers.image.title" = "blocky"
"org.opencontainers.image.vendor" = "Blocky"
"org.opencontainers.image.version" = "0.29.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"
