[metadata]
name = "fulcio"
version = "1.8.5"
description = "Fulcio - certificate authority for Sigstore"
vendor = "Sigstore"
source = "https://github.com/sigstore/fulcio"
license = "Apache-2.0"
tier = "standard"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/sigstore/fulcio/releases/download/v1.8.5/fulcio-linux-amd64"

[runtime]
entrypoint = ["/fulcio"]

[ports]
expose = [5555, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/sigstore/fulcio"
"org.opencontainers.image.title" = "fulcio"
"org.opencontainers.image.vendor" = "sigstore"
"org.opencontainers.image.version" = "1.8.5"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "security"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"
