[metadata]
name = "mythtv"
version = "34.0"
description = "mythtv container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["mythbackend"]

[ports]
expose = [6543, 9101]

[labels]
"org.opencontainers.image.title" = "mythtv"
"org.opencontainers.image.vendor" = "MythTV"
"org.opencontainers.image.version" = "34.0"
"sovereign.base.image" = "wolfi"
"sovereign.constraint.nonroot" = "true"
"sovereign.health.type" = "exec"
"sovereign.image.tier" = "3"
"sovereign.metrics.native" = "ztunnel"

