[metadata]
name = "cockroachdb"
version = "23.2.3"
description = "CockroachDB - distributed SQL database"
vendor = "Cockroach Labs"
source = "https://github.com/cockroachdb/cockroach"
license = "BSL-1.1"
tier = "1"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/cockroachdb/cockroachdb/releases/download/v23.2.3/cockroachdb-23.2.3-linux-amd64.tar.gz"

[runtime]
entrypoint = ["/usr/local/bin/cockroach"]

[ports]
expose = [26257, 9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened CockroachDB - distributed SQL database"
"org.opencontainers.image.title" = "cockroachdb"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.health.type" = "exec"
"evergreen.image.category" = "database"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

