version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'

    labels:
      - 'dependencies'
      - 'docker'
      - 'automated'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'

    reviewers:
      - 'WyattAu'
    assignees:
      - 'WyattAu'

    auto_merge:
      - dependency_type: 'all'
        update_types: ['version-update:semver-minor', 'version-update:semver-patch']
