version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    reviewers:
      - "WyattAu"
    groups:
      docker-images:
        patterns:
          - "*"
