version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/" 
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "docker"
    groups:
      docker-images:
        patterns:
          - "*"