[metadata]
tier = "standard"
name = "roundcube"
version = "1.6.9"
description = "Roundcube - feature-rich webmail client"
vendor = "roundcube"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/roundcube/roundcubemail/releases/download/1.6.9/roundcubemail-1.6.9-complete.tar.gz"

[runtime]
entrypoint = ["php-fpm83"]
cmd = ["-F"]

[ports]
expose = [8888, 9101]

[labels]
"org.opencontainers.image.description" = "Roundcube - feature-rich webmail client"
"org.opencontainers.image.source" = "https://github.com/roundcube/roundcubemail"
"org.opencontainers.image.title" = "roundcube"
"org.opencontainers.image.vendor" = "Roundcube"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "tcp"
"evergreen.image.category" = "email"
"evergreen.image.tier" = "standard""evergreen.metrics.native" = "ztunnel"
