[metadata]
tier = "standard"
name = "nextcloud-ocis"
version = "v8.0.1"
description = "nextcloud-ocis container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/nextcloud-ocis"]

[ports]
expose = [9200, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/owncloud/ocis"
"org.opencontainers.image.title" = "nextcloud-ocis"
"org.opencontainers.image.vendor" = "Nextcloud"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.constraint.base" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "5s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "10000ms"
"evergreen.image.category" = "cloud-storage"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "standard""evergreen.metrics.native" = "ztunnel"
