[metadata]
tier = "standard"
name = "maven"
version = "3.9.15"
description = "Evergreen hardened maven - Java build tool"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["mvn"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened maven - Java build tool"
"org.opencontainers.image.title" = "maven"
"org.opencontainers.image.vendor" = "Apache"
"org.opencontainers.image.version" = "3.9.15"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.shutdown-timeout" = "30s"
"evergreen.hft.signal-handling" = "native"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"

