[metadata]
tier = "standard"
name = "whoogle-search"
version = "unknown"
description = "Whoogle - Privacy-friendly search proxy"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://hub.docker.com/_/benbusby-whoogle-search"
[runtime]
entrypoint = ["whoogle-search"]
cmd = ["--port", "5000"]

[ports]
expose = [5000, 9101]

[labels]
"org.opencontainers.image.description" = "Whoogle - Privacy-friendly search proxy"
"org.opencontainers.image.source" = "https://github.com/benbusby/whoogle-search"
"org.opencontainers.image.title" = "whoogle-search"
"org.opencontainers.image.vendor" = "benbusby"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
