[metadata]
name = "nginx-ingress-controller"
version = "1.10.1"
description = "nginx-ingress-controller container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/nginx-ingress-controller"]

[ports]
expose = [80, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/kubernetes/ingress-nginx"
"org.opencontainers.image.title" = "nginx-ingress-controller"
"org.opencontainers.image.vendor" = "Kubernetes"
"org.opencontainers.image.version" = "1.10.1"
"sovereign.base.image" = "scratch"
"sovereign.constraint.nonroot" = "true"
"sovereign.constraint.scratch" = "true"
"sovereign.health.type" = "exec"
"sovereign.hft.init-system" = "none"
"sovereign.hft.shutdown-timeout" = "3s"
"sovereign.hft.signal-handling" = "native"
"sovereign.hft.startup-timeout" = "5000ms"
"sovereign.image.category" = "networking"
"sovereign.image.status" = "functional"
"sovereign.image.tier" = "1"
"sovereign.metrics.native" = "ztunnel"

