[metadata]
tier = "standard"
name = "rclone"
version = "v1.69.1"
description = "rclone container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://hub.docker.com/_/rclone-rclone"
[runtime]
entrypoint = ["/rclone"]

[ports]
expose = [5572, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/rclone/rclone"
"org.opencontainers.image.title" = "rclone"
"org.opencontainers.image.vendor" = "Rclone"
"org.opencontainers.image.version" = "v1.69.1"
"evergreen.base.image" = "scratch"
"evergreen.constraint.base" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "5s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "10000ms"
"evergreen.image.category" = "cloud-storage"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
