repos:
  # Standard hooks for file cleanup
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict

  # Prettier for auto-formatting MD and YAML files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8 # Use a specific version for consistency
    hooks:
      - id: prettier
        types: [yaml, markdown]
        args: [--config, .prettierrc.yml]

  # Linters for style and correctness
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        args: [--config, .markdownlint.yml, "**/*.md"]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--config-file, .yamllint.yml]

  # Linter for Dockerfiles, running via Docker for consistency.
  - repo: local
    hooks:
      - id: hadolint
        name: Hadolint (Dockerfile Linter via Docker)
        # Use the 'docker_image' language to run this hook inside a container.
        language: docker_image
        # Specify the official hadolint image and a specific version for reproducibility.
        entry: hadolint/hadolint:v2.12.0 hadolint
        types: [dockerfile]
