[metadata]
tier = "standard"
name = "ldap"
version = "2.6.8"
description = "ldap container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "ldap"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["slapd"]

[ports]
expose = [389, 9101]

[labels]
"org.opencontainers.image.title" = "ldap"
"org.opencontainers.image.vendor" = "OpenLDAP"
"org.opencontainers.image.version" = "2.6.8"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"
