[metadata]
tier = "standard"
name = "llama-cpp-server"
version = "b5415"
description = "llama-cpp-server container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/llama-server"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/ggerganov/llama.cpp/releases"
"org.opencontainers.image.title" = "llama-cpp-server"
"org.opencontainers.image.vendor" = "ggerganov/llama.cpp"
"org.opencontainers.image.version" = "b5415"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"

