[metadata]
name = "oracledb-xe"
version = "21.3.0"
description = "Evergreen hardened Oracle DB XE - extracted from gvenzl/oracle-xe"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "gvenzl/oracle-xe:21-slim"

[runtime]
entrypoint = ["/opt/oracle/opt/oracle/product/21c/dbhomeXE/bin/sqlplus"]

[ports]
expose = [1521, 9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened Oracle DB XE - extracted from gvenzl/oracle-xe"
"org.opencontainers.image.title" = "oracledb-xe"
"org.opencontainers.image.vendor" = "Oracle"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.category" = "database"
"evergreen.image.note" = "Extracted from gvenzl/oracle-xe:21-slim community image. Oracle license applies."
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

