[metadata]
name = "cockroachdb-sql"
version = "23.2.3"
description = "Evergreen hardened CockroachDB SQL Shell - distributed SQL interactive client"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/usr/local/bin/cockroach"]
cmd = ["sql", "--insecure"]

[ports]
expose = [26257, 9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened CockroachDB SQL Shell - distributed SQL interactive client"
"org.opencontainers.image.title" = "cockroachdb-sql"
"org.opencontainers.image.vendor" = "Cockroach Labs"
"org.opencontainers.image.version" = "23.2.3"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.connection-drain" = "false"
"evergreen.hft.cpu-pins" = "6-7"
"evergreen.hft.cpu-pins-mode" = "shared"
"evergreen.hft.deploy-strategy" = "standard-rolling"
"evergreen.hft.init-system" = "none"
"evergreen.hft.pre-stop-hook" = "false"
"evergreen.hft.sched-policy" = "SCHED_OTHER"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "database"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

