[metadata]
name = "etcd"
version = "3.6.10"
description = "etcd - distributed reliable key-value store"
vendor = "CNCF"
source = "https://github.com/etcd-io/etcd"
license = "Apache-2.0"
tier = "2"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/etcd-io/etcd/releases/download/v3.6.10/etcd-v3.6.10-linux-amd64.tar.gz"

[runtime]
entrypoint = ["/etcd"]

[ports]
expose = [2379, 9101]

[labels]
"org.opencontainers.image.title" = "etcd"
"org.opencontainers.image.vendor" = "etcd"
"org.opencontainers.image.version" = "3.6.10"
"sovereign.base.image" = "scratch"
"sovereign.constraint.nonroot" = "true"
"sovereign.constraint.scratch" = "true"
"sovereign.health.type" = "exec"
"sovereign.hft.connection-drain" = "true"
"sovereign.hft.cpu-pins" = "4-5"
"sovereign.hft.cpu-pins-mode" = "exclusive"
"sovereign.hft.deploy-strategy" = "hft-stateful"
"sovereign.hft.init-system" = "none"
"sovereign.hft.pre-stop-delay" = "5s"
"sovereign.hft.pre-stop-hook" = "true"
"sovereign.hft.sched-policy" = "SCHED_OTHER"
"sovereign.hft.shutdown-timeout" = "3s"
"sovereign.hft.signal-handling" = "native"
"sovereign.hft.startup-timeout" = "3000ms"
"sovereign.image.tier" = "1"
"sovereign.metrics.native" = "ztunnel"

