[metadata]
tier = "standard"
name = "timescaledb"
version = "2.15.0"
description = "timescaledb container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["postgres"]

[ports]
expose = [5432, 9101]

[labels]
"org.opencontainers.image.title" = "timescaledb"
"org.opencontainers.image.vendor" = "Timescale"
"org.opencontainers.image.version" = "2.15.0"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.hardened" = "true"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
