[metadata]
tier = "standard"
name = "lazydocker-ui"
version = "0.25.2"
description = "lazydocker-ui container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/jesseduffield/lazydocker"
[runtime]
entrypoint = ["/lazydocker"]
cmd = ["--help"]

[ports]
expose = [9101]

[labels]
"evergreen.base.image" = "scratch"
"evergreen.health.type" = "exec"
"evergreen.metrics.native" = "ztunnel"
