[metadata]
name = "surrealdb"
version = "3.0.5"
description = "surrealdb container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/surreal"]

[ports]
expose = [8000, 9101]

[labels]
"org.opencontainers.image.title" = "surrealdb"
"org.opencontainers.image.vendor" = "Surrealdb"
"org.opencontainers.image.version" = "3.0.5"
"sovereign.base.image" = "scratch"
"sovereign.constraint.nonroot" = "true"
"sovereign.constraint.scratch" = "true"
"sovereign.health.type" = "exec"
"sovereign.hft.init-system" = "none"
"sovereign.hft.shutdown-timeout" = "3s"
"sovereign.hft.signal-handling" = "native"
"sovereign.hft.startup-timeout" = "3000ms"
"sovereign.image.tier" = "1"
"sovereign.metrics.native" = "ztunnel"

