[metadata]
tier = "standard"
name = "mariadb-operator"
version = "26.3.0"
description = "MariaDB Operator for Kubernetes"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "ghcr.io/mariadb-operator/mariadb-operator:v${VERSION}"

[runtime]
entrypoint = ["/usr/local/bin/mariadb-operator"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.description" = "MariaDB Operator for Kubernetes"
"org.opencontainers.image.source" = "https://github.com/mariadb-operator/mariadb-operator"
"org.opencontainers.image.title" = "mariadb-operator"
"org.opencontainers.image.vendor" = "mariadb-operator"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
