[metadata]
name = "mongodb-5"
version = "5.0"
description = "Sovereign hardened MongoDB 5.0 - document database"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "mongo:${VERSION}"

[runtime]
entrypoint = ["mongod"]

[ports]
expose = [27017, 9101]

[labels]
"org.opencontainers.image.description" = "Sovereign hardened MongoDB 5.0 - document database"
"org.opencontainers.image.title" = "mongodb-5"
"org.opencontainers.image.vendor" = "MongoDB"
"org.opencontainers.image.version" = "${VERSION}"
"sovereign.base.image" = "wolfi"
"sovereign.constraint.nonroot" = "true"
"sovereign.health.type" = "exec"
"sovereign.image.category" = "database"
"sovereign.image.status" = "functional"
"sovereign.image.tier" = "1"
"sovereign.metrics.native" = "ztunnel"

