[metadata]
name = "trivy"
version = "0.70.0"
description = "Trivy - security scanner for containers and dependencies"
vendor = "Aqua Security"
source = "https://github.com/aquasecurity/trivy"
license = "Apache-2.0"
tier = "critical"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/aquasecurity/trivy/releases/download/v0.70.0/trivy_0.70.0_Linux-64bit.tar.gz"

[runtime]
entrypoint = ["/trivy"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/aquasecurity/trivy"
"org.opencontainers.image.title" = "trivy"
"org.opencontainers.image.vendor" = "Aqua Security"
"org.opencontainers.image.version" = "0.70.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "security"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"
