apiVersion: v2
name: jenkins
description: "Automation server for CI/CD — Evergreen Image Registry hardened image"
type: application
version: 0.1.0
appVersion: "latest"
maintainers:
  - name: Wyatt Au
keywords:
  - jenkins
  - security
  - hardened
  - evergreen
home: https://github.com/WyattAu/EvergreenImageRegistry/tree/main/images/jenkins
sources:
  - https://github.com/WyattAu/EvergreenImageRegistry
