[metadata]
name = "ulogger"
version = "latest"
description = "ulogger - log collection tool"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["ulogger"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.description" = "ulogger - log collection tool"
"org.opencontainers.image.source" = "https://github.com/nicehash/ulogger"
"org.opencontainers.image.title" = "ulogger"
"org.opencontainers.image.vendor" = "nicehash"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"

