[metadata]
tier = "standard"
name = "stalwart"
version = "0.16.2"
description = "Stalwart Mail Server - all-in-one mail server written in Rust"
vendor = "stalwartlabs"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/stalwartlabs/stalwart/releases/download/v0.16.2/stalwart-x86_64-unknown-linux-musl.tar.gz"

[runtime]
entrypoint = ["/usr/local/bin/stalwart"]
cmd = ["mail"]

[ports]
expose = [25, 9101]

[labels]
"org.opencontainers.image.description" = "Stalwart Mail Server - all-in-one mail server written in Rust"
"org.opencontainers.image.source" = "https://github.com/stalwartlabs/stalwart"
"org.opencontainers.image.title" = "stalwart"
"org.opencontainers.image.vendor" = "stalwartlabs"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "tcp"
"evergreen.image.category" = "email"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"
