[metadata]
tier = "standard"
name = "falco-rules"
version = "unknown"
description = "Falco - rules only"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://hub.docker.com/_/falcosecurity-falco-0.38.1"
[runtime]
entrypoint = ["cat"]
cmd = ["/app/rules/rules.yaml"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.description" = "Falco - rules only"
"org.opencontainers.image.source" = "https://github.com/falcosecurity/rules"
"org.opencontainers.image.title" = "falco-rules"
"org.opencontainers.image.vendor" = "Sysdig"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
