[metadata]
tier = "standard"
name = "espocrm"
version = "8.3.2"
description = "espocrm container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["php-fpm8.4"]

[ports]
expose = [80, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/espocrm/espocrm"
"org.opencontainers.image.title" = "espocrm"
"org.opencontainers.image.vendor" = "EspoCRM"
"org.opencontainers.image.version" = "8.3.2"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.base" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "10s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "30000ms"
"evergreen.image.category" = "crm-erp"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
