[metadata]
name = "crowdsec-lapi"
version = "1.7.7"
description = "crowdsec-lapi container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/crowdsec"]
cmd = ["-c /app/config.yaml -lapi"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/crowdsecurity/crowdsec"
"org.opencontainers.image.title" = "crowdsec-lapi"
"org.opencontainers.image.vendor" = "CrowdSecurity"
"org.opencontainers.image.version" = "1.7.7"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "security"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

