[metadata]
tier = "standard"
name = "renovate"
version = "43.160.6"
description = "renovate container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["renovate"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/renovatebot/renovate"
"org.opencontainers.image.title" = "renovate"
"org.opencontainers.image.vendor" = "RenovateBot"
"org.opencontainers.image.version" = "43.160.6"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.base" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "30s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "30000ms"
"evergreen.image.category" = "automation"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "standard""evergreen.metrics.native" = "ztunnel"
