[metadata]
tier = "standard"
name = "dockerfile-lint"
version = "unknown"
description = "Dockerfile linter"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["dockerfilelint"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.description" = "Dockerfile linter"
"org.opencontainers.image.title" = "dockerfile-lint"
"org.opencontainers.image.vendor" = "replicated"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"
