[metadata]
name = "redis-exporter"
version = "1.82.0"
description = "Redis Exporter - Prometheus exporter for Redis"
vendor = "Prometheus"
source = "https://github.com/oliver006/redis_exporter"
license = "Apache-2.0"
tier = "2"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/redis-exporter/redis-exporter/releases/download/v1.82.0/redis-exporter-1.82.0-linux-amd64.tar.gz"

[runtime]
entrypoint = ["/redis_exporter"]

[ports]
expose = [9121, 9101]

[labels]
"org.opencontainers.image.title" = "redis-exporter"
"org.opencontainers.image.vendor" = "Prometheus"
"org.opencontainers.image.version" = "1.82.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

