[metadata]
tier = "standard"
name = "docker-clean"
version = "0.3.0"
description = "Docker cleanup and pruning tool"
vendor = "zzehring"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["docker-clean"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.description" = "Docker cleanup and pruning tool"
"org.opencontainers.image.source" = "https://github.com/zzehring/docker-cleanup"
"org.opencontainers.image.title" = "docker-clean"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.category" = "devops"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"

