[metadata]
name = "mongodb"
version = "7.0.11"
description = "MongoDB - document-oriented NoSQL database"
vendor = "MongoDB"
source = "https://github.com/mongodb/mongo"
license = "SSPL"
tier = "critical"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/mongodb/mongodb/releases/download/v7.0.11/mongodb-7.0.11-linux-amd64.tar.gz"

[runtime]
entrypoint = ["sh", "-c", "mongod"]

[ports]
expose = [27017, 9101]

[labels]
"org.opencontainers.image.title" = "mongodb"
"org.opencontainers.image.vendor" = "MongoDB"
"org.opencontainers.image.version" = "7.0.11"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.hardened" = "true"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "http"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "true"

