apiVersion: v2
name: docker-socket-proxy
description: "Container image — Evergreen Image Registry hardened image"
type: application
version: 0.1.0
appVersion: "latest"
maintainers:
  - name: Wyatt Au
keywords:
  - docker-socket-proxy
  - security
  - hardened
  - evergreen
home: https://github.com/WyattAu/EvergreenImageRegistry/tree/main/images/docker-socket-proxy
sources:
  - https://github.com/WyattAu/EvergreenImageRegistry
