[metadata]
tier = "standard"
name = "budibase-worker"
version = "2.14.0"
description = "budibase-worker container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["node"]

[ports]
expose = [10001, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/Budibase/budibase/releases"
"org.opencontainers.image.title" = "budibase-worker"
"org.opencontainers.image.vendor" = "Budibase/budibase"
"org.opencontainers.image.version" = "2.14.0"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.hardened" = "true"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "standard""evergreen.metrics.native" = "ztunnel"
