[metadata]
tier = "standard"
name = "keycloak-operator"
version = "26.6.1"
description = "keycloak-operator container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "quay.io/keycloak/keycloak-operator:${VERSION}"

[runtime]
entrypoint = ["/usr/local/bin/keycloak-operator"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/keycloak/keycloak-operator"
"org.opencontainers.image.title" = "keycloak-operator"
"org.opencontainers.image.vendor" = "Keycloak"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "identity"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "standard""evergreen.metrics.native" = "ztunnel"
