[metadata]
name = "meltano"
version = "3.7.0"
description = "meltano container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["meltano"]

[ports]
expose = [5000, 9101]

[labels]
"org.opencontainers.image.title" = "meltano"
"org.opencontainers.image.vendor" = "Meltano"
"org.opencontainers.image.version" = "3.7.0"
"sovereign.base.image" = "wolfi"
"sovereign.constraint.nonroot" = "true"
"sovereign.health.type" = "exec"
"sovereign.image.tier" = "3"
"sovereign.metrics.native" = "ztunnel"

