apiVersion: v2
name: portainer-agent
description: "Container image — Evergreen Image Registry hardened image"
type: application
version: 0.1.0
appVersion: "latest"
maintainers:
  - name: Wyatt Au
keywords:
  - portainer-agent
  - security
  - hardened
  - evergreen
home: https://github.com/WyattAu/EvergreenImageRegistry/tree/main/images/portainer-agent
sources:
  - https://github.com/WyattAu/EvergreenImageRegistry
