[metadata]
name = "openhab"
version = "5.2.0.M3"
description = "openhab container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/openhab/start.sh"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/openhab/openhab-distro"
"org.opencontainers.image.title" = "openhab"
"org.opencontainers.image.vendor" = "OpenHAB"
"org.opencontainers.image.version" = "4.3.11"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.official" = "true"
"evergreen.health.type" = "none"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"

