[metadata]
tier = "standard"
name = "navidrome-sqlite"
version = "0.52.5"
description = "navidrome-sqlite container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://hub.docker.com/_/deluan-navidrome"
[runtime]
entrypoint = ["/navidrome"]

[ports]
expose = [4533, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/navidrome/navidrome/releases/download/v0.52.5"
"org.opencontainers.image.title" = "navidrome-sqlite"
"org.opencontainers.image.vendor" = "navidrome/navidrome"
"org.opencontainers.image.version" = "0.52.5"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
