[metadata]
name = "telegraf"
version = "1.30.3"
description = "Telegraf - metrics collection agent"
vendor = "InfluxData"
source = "https://github.com/influxdata/telegraf"
license = "Apache-2.0"
tier = "standard"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/telegraf/telegraf/releases/download/v1.30.3/telegraf-1.30.3-linux-amd64.tar.gz"

[runtime]
entrypoint = ["/usr/bin/telegraf"]

[ports]
expose = [8125, 9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened Telegraf - metrics collection agent by InfluxData"
"org.opencontainers.image.title" = "telegraf"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.health.type" = "exec"
"evergreen.image.category" = "monitoring"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"
