[metadata]
tier = "standard"
name = "outline"
version = "0.77.0"
description = "outline container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "outline"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["node"]

[ports]
expose = [3000, 9101]

[labels]
"org.opencontainers.image.title" = "outline"
"org.opencontainers.image.vendor" = "Outline"
"org.opencontainers.image.version" = "0.77.0"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"

