[metadata]
tier = "standard"
name = "buildkit"
version = "0.29.0"
description = "Evergreen hardened buildkit - concurrent build toolkit"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["buildkitd"]

[ports]
expose = [1234, 9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened buildkit - concurrent build toolkit"
"org.opencontainers.image.title" = "buildkit"
"org.opencontainers.image.vendor" = "Moby"
"org.opencontainers.image.version" = "0.29.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.shutdown-timeout" = "10s"
"evergreen.hft.signal-handling" = "native"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
