[metadata]
name = "vault-csi-provider"
version = "1.7.1"
description = "vault-csi-provider container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "hashicorp/vault-csi-provider:${VERSION}"

[runtime]
entrypoint = ["/usr/local/bin/vault-csi-provider"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/hashicorp/vault-csi-provider"
"org.opencontainers.image.title" = "vault-csi-provider"
"org.opencontainers.image.vendor" = "HashiCorp"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "secrets"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"

