[metadata]
tier = "standard"
name = "authelia-lite"
version = "4.39.19"
description = "Evergreen hardened Authelia-lite - lightweight SSO/2FA authentication portal"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/usr/local/bin/authelia"]

[ports]
expose = [80, 9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened Authelia-lite - lightweight SSO/2FA authentication portal"
"org.opencontainers.image.title" = "authelia-lite"
"org.opencontainers.image.vendor" = "Authelia"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.image.category" = "security"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
