apiVersion: v2
name: dex
description: "OpenID Connect identity provider — Evergreen Image Registry hardened image"
type: application
version: 0.1.0
appVersion: "latest"
maintainers:
  - name: Wyatt Au
keywords:
  - dex
  - security
  - hardened
  - evergreen
home: https://github.com/WyattAu/EvergreenImageRegistry/tree/main/images/dex
sources:
  - https://github.com/WyattAu/EvergreenImageRegistry
