[metadata]
tier = "standard"
name = "prowlarr-develop"
version = "2.3.6.5351"
description = "prowlarr-develop container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/app/Prowlarr"]

[ports]
expose = [9696, 9101]

[labels]
"org.opencontainers.image.title" = "prowlarr-develop"
"evergreen.health.type" = "exec"
"evergreen.metrics.native" = "ztunnel"
