[metadata]
tier = "standard"
name = "trivy-k8s"
version = "0.70.0"
description = "trivy-k8s container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/trivy"]
cmd = ["--help"]

[ports]
expose = [9101]

[labels]
"evergreen.base.image" = "scratch"
"evergreen.health.type" = "exec"
"evergreen.metrics.native" = "ztunnel"
