[metadata]
name = "modsecurity-crs"
version = "3.3.5"
description = "Evergreen hardened ModSecurity CRS - OWASP Core Rule Set"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/usr/sbin/apache2", "-D", "FOREGROUND"]

[ports]
expose = [80, 9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened ModSecurity CRS - OWASP Core Rule Set"
"org.opencontainers.image.title" = "modsecurity-crs"
"org.opencontainers.image.vendor" = "OWASP"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.category" = "security"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

