[metadata]
tier = "standard"
name = "postgresql-17"
version = "17.2"
description = "PostgreSQL 17 Database Server"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["postgres"]

[ports]
expose = [5432, 9101]

[labels]
"org.opencontainers.image.description" = "PostgreSQL 17 Database Server"
"org.opencontainers.image.source" = "https://www.postgresql.org/"
"org.opencontainers.image.title" = "postgresql-17"
"org.opencontainers.image.vendor" = "PostgreSQL Global Development Group"
"org.opencontainers.image.version" = "17.2"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"
