[metadata]
tier = "standard"
name = "erpnext"
version = "15.11.0"
description = "erpnext container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "erpnext"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["python3"]

[ports]
expose = [8000, 9101]

[labels]
"org.opencontainers.image.title" = "erpnext"
"org.opencontainers.image.vendor" = "ERPNext"
"org.opencontainers.image.version" = "15.11.0"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"

