[metadata]
name = "tinytinyrss"
version = "24.5"
description = "tinytinyrss container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["php"]

[ports]
expose = [80, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/rr-/tt-rss/releases"
"org.opencontainers.image.title" = "tinytinyrss"
"org.opencontainers.image.vendor" = "tt-rss"
"org.opencontainers.image.version" = "24.5"
"sovereign.base.image" = "wolfi"
"sovereign.constraint.nonroot" = "true"
"sovereign.health.type" = "exec"
"sovereign.image.tier" = "3"
"sovereign.metrics.native" = "ztunnel"

