[metadata]
tier = "standard"
name = "snyk-monitor"
version = "1.1295.0"
description = "snyk-monitor container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/snyk-monitor"]
cmd = ["--help"]

[ports]
expose = [9101]

[labels]
"evergreen.base.image" = "scratch"
"evergreen.health.type" = "exec"
"evergreen.metrics.native" = "ztunnel"
