[metadata]
tier = "standard"
name = "smartdns"
version = "Release48"
description = "Local DNS server with DoH/DoT support"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/usr/local/bin/smartdns"]

[ports]
expose = [53, 9101]

[labels]
"org.opencontainers.image.description" = "Local DNS server with DoH/DoT support"
"org.opencontainers.image.source" = "https://github.com/pymumu/smartdns"
"org.opencontainers.image.title" = "smartdns"
"org.opencontainers.image.vendor" = "pymumu"
"org.opencontainers.image.version" = "Release48"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.base" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "dns"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
