[metadata]
tier = "standard"
name = "badger"
version = "4.2.0"
description = "Evergreen hardened Badger - embedded key-value store (Dgraph)"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"
multiarch = false

[source]
type = "package-manager"

[runtime]
entrypoint = ["/usr/local/bin/badger"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened Badger - embedded key-value store (Dgraph)"
"org.opencontainers.image.title" = "badger"
"org.opencontainers.image.vendor" = "Dgraph Labs"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.image.category" = "database"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
