[metadata]
tier = "standard"
name = "dragonfly-client"
version = "1.18.0"
description = "dragonfly-client container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/dfly"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/dragonflydb/dragonfly"
"org.opencontainers.image.title" = "dragonfly-client"
"org.opencontainers.image.vendor" = "DragonflyDB"
"org.opencontainers.image.version" = "1.18.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "none"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "database"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

