[metadata]
tier = "standard"
name = "cassandra-operator"
version = "1.20.0"
description = "Evergreen hardened cass-operator - Kubernetes operator for Apache Cassandra"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "ghcr.io/k8ssandra/cass-operator:v${VERSION}"

[runtime]
entrypoint = ["/usr/local/bin/cass-operator"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened cass-operator - Kubernetes operator for Apache Cassandra"
"org.opencontainers.image.title" = "cassandra-operator"
"org.opencontainers.image.vendor" = "k8ssandra"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.category" = "database"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"
