[metadata]
name = "jellyfin-ffmpeg"
version = "7.1"
description = "jellyfin-ffmpeg container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/usr/local/bin/ffmpeg"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/jellyfin/jellyfin-ffmpeg"
"org.opencontainers.image.title" = "jellyfin-ffmpeg"
"org.opencontainers.image.vendor" = "Jellyfin"
"org.opencontainers.image.version" = "7.1"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.base" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "5s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "30000ms"
"evergreen.image.category" = "media-streaming"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"

