[metadata]
name = "forgejo"
version = "v15.0.4"
description = "Forgejo - community-owned lightweight software forge"
vendor = "Forgejo"
source = "https://codeberg.org/forgejo/forgejo"
license = "MIT"
tier = "critical"
upstream_version = "v15.0.4"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "binary"
url = "https://code.forgejo.org/forgejo/forgejo/releases/download/v15.0.2/forgejo-15.0.2-linux-amd64"

[runtime]
entrypoint = ["/usr/local/bin/forgejo"]

[ports]
expose = [3000, 22]

[labels]
"org.opencontainers.image.title" = "forgejo"
"org.opencontainers.image.vendor" = "Forgejo"
"org.opencontainers.image.version" = "15.0.2"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.wolfi" = "true"
"evergreen.health.type" = "http"
"evergreen.image.tier" = "critical"
