[metadata]
tier = "standard"
name = "dagster-logs"
version = "1.10.0"
description = "dagster-logs container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/dagster/code"
[runtime]
entrypoint = ["dagster-logs"]

[ports]
expose = [3000, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/dagster-io/dagster/releases"
"org.opencontainers.image.title" = "dagster-logs"
"org.opencontainers.image.vendor" = "Dagster"
"org.opencontainers.image.version" = "1.10.0"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
