[metadata]
name = "dagster-logs"
version = "1.10.0"
description = "dagster-logs container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["dagster-logs"]

[ports]
expose = [3000, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/dagster-io/dagster/releases"
"org.opencontainers.image.title" = "dagster-logs"
"org.opencontainers.image.vendor" = "Dagster"
"org.opencontainers.image.version" = "1.10.0"
"sovereign.base.image" = "wolfi"
"sovereign.constraint.nonroot" = "true"
"sovereign.health.type" = "exec"
"sovereign.image.tier" = "3"
"sovereign.metrics.native" = "ztunnel"

