[metadata]
tier = "standard"
name = "immudb-proxy"
version = "1.11.0"
description = "Evergreen hardened immudb-proxy - proxy mode for immudb"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "docker.io/codenotary/immudb:${VERSION}"

[runtime]
entrypoint = ["/usr/local/bin/immudb-proxy"]

[ports]
expose = [3323, 9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened immudb-proxy - proxy mode for immudb"
"org.opencontainers.image.title" = "immudb-proxy"
"org.opencontainers.image.vendor" = "Codenotary"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.category" = "security"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"
