[metadata]
tier = "standard"
name = "jaeger-query"
version = "1.55.0"
description = "jaeger-query container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/jaeger-query"]

[ports]
expose = [16686, 9101]

[labels]
"org.opencontainers.image.title" = "jaeger-query"
"org.opencontainers.image.vendor" = "JaegerTracing"
"org.opencontainers.image.version" = "1.55.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "observability"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

