[metadata]
name = "postgres"
version = "17.4"
description = "PostgreSQL - advanced open source relational database"
vendor = "PostgreSQL"
source = "https://github.com/postgres/postgres"
license = "PostgreSQL"
tier = "1"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/postgres/postgres/releases/download/v17.4/postgres-17.4-linux-amd64.tar.gz"

[runtime]
entrypoint = ["postgres"]

[ports]
expose = [5432, 9101]

[labels]
"org.opencontainers.image.title" = "postgres"
"org.opencontainers.image.vendor" = "PostgreSQL"
"org.opencontainers.image.version" = "17.4"
"sovereign.base.image" = "wolfi"
"sovereign.constraint.hardened" = "true"
"sovereign.constraint.nonroot" = "true"
"sovereign.health.type" = "exec"
"sovereign.hft.init-system" = "none"
"sovereign.hft.shutdown-timeout" = "3s"
"sovereign.hft.signal-handling" = "native"
"sovereign.hft.startup-timeout" = "3000ms"
"sovereign.image.tier" = "1"
"sovereign.metrics.native" = "ztunnel"

