[metadata]
name = "polaris"
version = "10.2.0"
description = "polaris - Evergreen hardened image"
vendor = "Evergreen"
source = "https://github.com/FairwindsOps/polaris"
license = "Apache-2.0"
tier = "standard"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "upstream-repack"
url = "https://github.com/FairwindsOps/polaris"

[runtime]
entrypoint = []

[ports]
expose = [8080, 9101]

[labels]
"evergreen.image.tier" = "standard"
