pub mod audit;
pub mod auto_version;
pub mod bump;
pub mod changelog;
pub mod ci_diff;
pub mod cli;
pub mod dashboard;
pub mod deprecated;
pub mod discover;
pub mod dockerfile_utils;
pub mod drift;
pub mod error;
pub mod generate;
pub mod manifest;
pub mod migrate;
pub mod outdated;
pub mod output;
pub mod patterns;
pub mod pin_digests;
pub mod registry_index;
pub mod report;
pub mod run;
pub mod sign;
pub mod snapshot;
pub mod validate_parallel;
pub mod validate_strict;
pub mod verify;
pub mod verify_all;

/// User-Agent header value, derived from Cargo.toml version at compile time.
pub const USER_AGENT: &str = concat!("evergreenctl/", env!("CARGO_PKG_VERSION"));
