[metadata]
tier = "standard"
name = "node-distroless"
version = "22.12.0"
description = "Evergreen hardened node-distroless - Node.js on distroless base"

[build]
base = "gcr.io/distroless/nodejs22-debian12@sha256:8a3e96fe3345b5d83ecec2066e7c498139a02a6d1214e4f6c39f9ce359f3f5bc"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/distroless/nodejs22-debian12"
[runtime]
entrypoint = ["node"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened node-distroless - Node.js on distroless base"
"org.opencontainers.image.title" = "node-distroless"
"org.opencontainers.image.vendor" = "Node.js"
"org.opencontainers.image.version" = "22.12.0"
"evergreen.base.image" = "distroless"
"evergreen.constraint.distroless" = "true"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.shutdown-timeout" = "5s"
"evergreen.hft.signal-handling" = "native"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
