[metadata]
tier = "standard"
name = "sql-ledger"
version = "2.8.38"
description = "sql-ledger container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["httpd", "-D", "FOREGROUND"]

[ports]
expose = [80, 9101]

[labels]
"org.opencontainers.image.source" = "https://www.ledgersmb.org/"
"org.opencontainers.image.title" = "sql-ledger"
"org.opencontainers.image.vendor" = "SQL-Ledger"
"org.opencontainers.image.version" = "2.8.38"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.base" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "10s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "30000ms"
"evergreen.image.category" = "business-finance"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "standard""evergreen.metrics.native" = "ztunnel"
