[metadata]
tier = "critical"
name = "mysql-operator"
version = "0.6.3"
description = "Presslabs MySQL Operator for Kubernetes"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "bitpoke/mysql-operator:v${VERSION}"

[runtime]
entrypoint = ["/usr/local/bin/mysql-operator"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.description" = "Presslabs MySQL Operator for Kubernetes"
"org.opencontainers.image.source" = "https://github.com/presslabs/mysql-operator"
"org.opencontainers.image.title" = "mysql-operator"
"org.opencontainers.image.vendor" = "Presslabs"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"
