[metadata]
name = "influxdb"
version = "2.7"
description = "InfluxDB - time series database for metrics and events"
vendor = "InfluxData"
source = "https://github.com/influxdata/influxdb"
license = "Apache-2.0"
tier = "standard"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "influxdb:2.7"

[runtime]
entrypoint = ["/influxd"]

[ports]
expose = [8086, 9101]

[labels]
"org.opencontainers.image.title" = "influxdb"
"org.opencontainers.image.vendor" = "InfluxData"
"org.opencontainers.image.version" = "2.7"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.connection-drain" = "true"
"evergreen.hft.cpu-pins" = "4-5"
"evergreen.hft.cpu-pins-mode" = "exclusive"
"evergreen.hft.deploy-strategy" = "hft-stateful"
"evergreen.hft.init-system" = "none"
"evergreen.hft.pre-stop-delay" = "5s"
"evergreen.hft.pre-stop-hook" = "true"
"evergreen.hft.sched-policy" = "SCHED_OTHER"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "tsdb"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"
