[metadata]
tier = "standard"
name = "zigbee2mqtt"
version = "unknown"
description = "Zigbee to MQTT bridge"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["node", "index.js"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.description" = "Zigbee to MQTT bridge"
"org.opencontainers.image.source" = "https://github.com/Koenkk/zigbee2mqtt"
"org.opencontainers.image.title" = "zigbee2mqtt"
"org.opencontainers.image.vendor" = "Koenkk"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "standard""evergreen.metrics.native" = "ztunnel"
