[metadata]
name = "gitlab-operator"
version = "0.8.0"
description = "GitLab Operator - Kubernetes operator for GitLab"
vendor = "GitLab"
source = "https://gitlab.com/gitlab-org/cloud-native/gitlab-operator"
license = "Apache-2.0"
tier = "2"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "registry.gitlab.com/gitlab-org/cloud-native/gitlab-operator:v${VERSION}"

[runtime]
entrypoint = ["/usr/local/bin/gitlab-operator"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.description" = "GitLab Operator - Kubernetes operator for GitLab"
"org.opencontainers.image.source" = "https://gitlab.com/gitlab-org/cloud-native/gitlab-operator"
"org.opencontainers.image.title" = "gitlab-operator"
"org.opencontainers.image.vendor" = "GitLab"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"

