# Default values for elasticsearch
image:
  name: elasticsearch
  tag: "latest"
  pullPolicy: IfNotPresent

tier: standard
replicas: 1

security:
  readOnlyRootFs: true

service:
  type: ClusterIP
  port: 8080

env: {}
envFrom: []

persistence:
  enabled: false
