[metadata]
tier = "standard"
name = "cors-proxy"
version = "1.25.5"
description = "cors-proxy container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/opt/nginx/sbin/nginx"]
cmd = ["-c", "/app/conf/nginx.conf", "-g", "daemon off;"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.source" = "https://nginx.org"
"org.opencontainers.image.title" = "cors-proxy"
"org.opencontainers.image.vendor" = "nginx"
"org.opencontainers.image.version" = "1.25.5"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.distrole" = "debian-slim"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "networking"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"
