[metadata]
tier = "standard"
name = "firebird"
version = "4.0.5"
description = "Evergreen hardened Firebird - SQL relational database"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/jacobalberty/firebird"
[runtime]
entrypoint = ["firebird"]

[ports]
expose = [3050, 9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened Firebird - SQL relational database"
"org.opencontainers.image.title" = "firebird"
"org.opencontainers.image.vendor" = "FirebirdSQL"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.category" = "database"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
