[metadata]
tier = "standard"
name = "jellyfin-server"
version = "10.11.8"
description = "jellyfin-server container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/app/jellyfin"]

[ports]
expose = [8096, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/jellyfin/jellyfin"
"org.opencontainers.image.title" = "jellyfin-server"
"org.opencontainers.image.vendor" = "Jellyfin"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.official" = "true"
"evergreen.health.type" = "none"
"evergreen.image.category" = "media"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"
