[metadata]
name = "snyk"
version = "1.1300.0"
description = "snyk container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/usr/local/bin/snyk"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/snyk/snyk"
"org.opencontainers.image.title" = "snyk"
"org.opencontainers.image.vendor" = "Snyk"
"org.opencontainers.image.version" = "1.1300.0"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.base" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "30s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "30000ms"
"evergreen.image.category" = "security"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"

