[metadata]
tier = "standard"
name = "cloudflare-warrior"
version = "2026.5.0"
description = "Cloudflare Tunnel client (cloudflared)"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/cloudflared"]
cmd = ["tunnel", "--no-autoupdate"]

[ports]
expose = [7844, 9101]

[labels]
"org.opencontainers.image.description" = "Cloudflare Tunnel client (cloudflared)"
"org.opencontainers.image.source" = "https://github.com/cloudflare/cloudflared"
"org.opencontainers.image.title" = "cloudflare-warrior"
"org.opencontainers.image.vendor" = "Cloudflare"
"org.opencontainers.image.version" = "2026.5.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "networking"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

