# STATPING - ARCHIVED
# See: https://github.com/statping/statping

FROM scratch
USER 65532:65532
LABEL org.opencontainers.image.title="statping" \
      sovereign.image.status="archived" \
      sovereign.image.note="Upstream project archived"

LABEL sovereign.base.image="scratch"
LABEL sovereign.metrics.native="ztunnel"
LABEL sovereign.health.type="none"
EXPOSE 9101
STOPSIGNAL SIGTERM
