[metadata]
name = "immich-server"
version = "1.106.0"
description = "immich-server container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["node"]

[ports]
expose = [3001, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/immich-app/immich/releases"
"org.opencontainers.image.title" = "immich-server"
"org.opencontainers.image.vendor" = "immich-app/immich"
"org.opencontainers.image.version" = "1.106.0"
"sovereign.base.image" = "wolfi"
"sovereign.constraint.hardened" = "true"
"sovereign.constraint.nonroot" = "true"
"sovereign.health.type" = "exec"
"sovereign.image.tier" = "3"
"sovereign.metrics.native" = "ztunnel"

