[metadata]
name = "immich-server"
version = "2.7.5"
description = "immich-server container image"
tier = "critical"
upstream_version = "2.7.5"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["node"]

[ports]
expose = [3001, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/immich-app/immich/releases"
"org.opencontainers.image.title" = "immich-server"
"org.opencontainers.image.vendor" = "immich-app/immich"
"org.opencontainers.image.version" = "2.7.5"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.hardened" = "true"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "critical"
"evergreen.metrics.native" = "ztunnel"
