[metadata]
name = "mariadb-10"
version = "10.11.6"
description = "Evergreen hardened MariaDB 10.x - LTS SQL database"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["mariadbd"]

[ports]
expose = [3306, 9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened MariaDB 10.x - LTS SQL database"
"org.opencontainers.image.title" = "mariadb-10"
"org.opencontainers.image.vendor" = "MariaDB"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.category" = "database"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

