[metadata]
tier = "standard"
name = "bundler"
version = "2.5.0"
description = "bundler container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["bundle"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/rubygems/rubygems"
"org.opencontainers.image.title" = "bundler"
"org.opencontainers.image.vendor" = "Ruby Bundler"
"org.opencontainers.image.version" = "2.5.0"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"

