[metadata]
tier = "standard"
name = "litellm"
version = "1.60.0"
description = "litellm container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["python3"]

[ports]
expose = [4000, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/BerriAI/litellm"
"org.opencontainers.image.title" = "litellm"
"org.opencontainers.image.vendor" = "LiteLLM"
"org.opencontainers.image.version" = "1.60.0"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"
