[metadata]
tier = "standard"
name = "sqlpage"
version = "0.43.0"
description = "SQL-only web application framework"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "source-build"
url = "https://github.com/sqlpage/SQLPage"
language = "rust"
target = "x86_64-unknown-linux-musl"

[runtime]
entrypoint = ["/sqlpage"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.title" = "sqlpage"
"org.opencontainers.image.source" = "https://github.com/sqlpage/SQLPage"
"org.opencontainers.image.version" = "0.43.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "web"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "prometheus"
