[metadata]
tier = "standard"
name = "courier-imap"
version = "5.1.4"
description = "courier-imap container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[ports]
expose = [143, 9101]

[labels]
"evergreen.base.image" = "wolfi"
"evergreen.health.type" = "exec"
"evergreen.metrics.native" = "ztunnel"

