[metadata]
tier = "standard"
name = "vecs-db"
version = "0.4.0"
description = "vecs-db container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["python3"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/supabase/vecs"
"org.opencontainers.image.title" = "vecs-db"
"org.opencontainers.image.vendor" = "Vecs"
"org.opencontainers.image.version" = "0.4.0"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
