[metadata]
tier = "standard"
name = "pgbouncer"
version = "1.22.1"
description = "pgbouncer container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "pgbouncer"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["pgbouncer"]

[ports]
expose = [6432, 9101]

[labels]
"org.opencontainers.image.title" = "pgbouncer"
"org.opencontainers.image.vendor" = "PgBouncer"
"org.opencontainers.image.version" = "1.22.1"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "standard""evergreen.metrics.native" = "ztunnel"
