[metadata]
name = "trivy-iac"
version = "0.70.0"
description = "trivy-iac container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/trivy"]
cmd = ["--help"]

[ports]
expose = [9101]

[labels]
"sovereign.base.image" = "scratch"
"sovereign.health.type" = "exec"
"sovereign.metrics.native" = "ztunnel"

