[metadata]
name = "postgres-exporter"
version = "0.17.0"
upstream_version = "0.17.0"
description = "Postgres Exporter - Prometheus exporter for PostgreSQL"
vendor = "Prometheus Community"
source = "https://github.com/prometheus-community/postgres_exporter"
license = "Apache-2.0"
tier = "critical"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "binary-release"
url = "https://github.com/prometheus-community/postgres_exporter/releases/download/v0.17.0/postgres_exporter-0.17.0.linux-amd64.tar.gz"

[runtime]
entrypoint = ["/postgres_exporter"]

[ports]
expose = [9187, 9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened Postgres Exporter - Prometheus exporter for PostgreSQL"
"org.opencontainers.image.title" = "postgres-exporter"
"org.opencontainers.image.vendor" = "Prometheus Community"
"org.opencontainers.image.version" = "0.17.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.connection-drain" = "false"
"evergreen.hft.cpu-pins" = "6-7"
"evergreen.hft.cpu-pins-mode" = "shared"
"evergreen.hft.deploy-strategy" = "standard-rolling"
"evergreen.hft.init-system" = "none"
"evergreen.hft.pre-stop-hook" = "false"
"evergreen.hft.sched-policy" = "SCHED_OTHER"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "database"
"evergreen.image.tier" = "critical"
"evergreen.metrics.native" = "ztunnel"
