[metadata]
name = "grafana-operator"
version = "5.22.2"
description = "Grafana Operator - manages Grafana instances on Kubernetes"
vendor = "Grafana Labs"
source = "https://github.com/grafana-operator/grafana-operator"
license = "Apache-2.0"
tier = "3"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "ghcr.io/grafana-operator/grafana-operator:v${VERSION}"

[runtime]
entrypoint = ["/usr/local/bin/grafana-operator"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.description" = "Sovereign hardened grafana-operator - Kubernetes Grafana operator"
"org.opencontainers.image.title" = "grafana-operator"
"org.opencontainers.image.vendor" = "Grafana"
"org.opencontainers.image.version" = "${VERSION}"
"sovereign.base.image" = "scratch"
"sovereign.constraint.nonroot" = "true"
"sovereign.constraint.scratch" = "true"
"sovereign.health.type" = "exec"
"sovereign.hft.shutdown-timeout" = "10s"
"sovereign.hft.signal-handling" = "native"
"sovereign.image.tier" = "3"
"sovereign.metrics.native" = "ztunnel"

