[metadata]
name = "jenkins-agent"
version = "3355.v388858a_47b_33"
description = "Evergreen hardened jenkins-agent - Jenkins SSH/JNLP agent"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["java", "-jar", "/app/agent.jar"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened jenkins-agent - Jenkins SSH/JNLP agent"
"org.opencontainers.image.title" = "jenkins-agent"
"org.opencontainers.image.vendor" = "Jenkins"
"org.opencontainers.image.version" = "3355.v388858a_47b_33"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.shutdown-timeout" = "30s"
"evergreen.hft.signal-handling" = "native"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"

