[metadata]
name = "mysql"
version = "8.4.1"
description = "MySQL - open source relational database management system"
vendor = "Oracle"
source = "https://github.com/mysql/mysql-server"
license = "GPL-2.0"
tier = "critical"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/mysql/mysql/releases/download/v8.4.1/mysql-8.4.1-linux-amd64.tar.gz"

[runtime]
entrypoint = ["sh", "-c", "mariadbd"]

[ports]
expose = [3306, 9101]

[labels]
"org.opencontainers.image.title" = "mysql"
"org.opencontainers.image.vendor" = "Oracle"
"org.opencontainers.image.version" = "8.4.1"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.hardened" = "true"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "http"
"evergreen.image.tier" = "critical"
"evergreen.metrics.native" = "true"
