[metadata]
tier = "standard"
name = "prometheus-x509-exporter"
version = "3.9.0"
description = "Prometheus exporter for X.509 certificate expiry metrics"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://hub.docker.com/_/enix-x509-certificate-exporter-3.10.0"
[runtime]
entrypoint = ["/x509-certificate-exporter"]

[ports]
expose = [9793, 9101]

[labels]
"org.opencontainers.image.description" = "Prometheus exporter for X.509 certificate expiry metrics"
"org.opencontainers.image.title" = "prometheus-x509-exporter"
"org.opencontainers.image.vendor" = "Enix"
"org.opencontainers.image.version" = "3.9.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.connection-drain" = "true"
"evergreen.hft.cpu-pins" = "4-5"
"evergreen.hft.cpu-pins-mode" = "exclusive"
"evergreen.hft.deploy-strategy" = "hft-stateful"
"evergreen.hft.init-system" = "none"
"evergreen.hft.pre-stop-delay" = "5s"
"evergreen.hft.pre-stop-hook" = "true"
"evergreen.hft.sched-policy" = "SCHED_OTHER"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
