[metadata]
name = "calibre-web"
version = "0.6.26"
description = "calibre-web container image"
tier = "critical"
upstream_version = "0.6.26"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "calibre"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["python"]

[ports]
expose = [8083, 9101]

[labels]
"org.opencontainers.image.title" = "calibre-web"
"org.opencontainers.image.vendor" = "Calibre-Web"
"org.opencontainers.image.version" = "0.6.26"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "critical"
"evergreen.metrics.native" = "ztunnel"
