[metadata]
name = "bind"
version = "9.21.21"
description = "BIND - DNS server software"
vendor = "ISC"
source = "https://github.com/isc-projects/bind9"
license = "Apache-2.0"
tier = "community"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/bind/bind/releases/download/v9.21.21/bind-9.21.21-linux-amd64.tar.gz"

[runtime]
entrypoint = ["/named"]

[ports]
expose = [53, 9101]

[labels]
"org.opencontainers.image.title" = "bind"
"org.opencontainers.image.vendor" = "ISC"
"org.opencontainers.image.version" = "9.21.21"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

