[metadata]
tier = "standard"
name = "mattermost"
version = "unknown"
description = "mattermost container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/opt/mattermost/bin/mattermost"]

[ports]
expose = [8065, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/mattermost/mattermost"
"org.opencontainers.image.title" = "mattermost"
"org.opencontainers.image.vendor" = "Mattermost"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.category" = "collaboration"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"
