[metadata]
name = "alertmanager"
version = "0.32.1"
description = "Alertmanager - handles alerts sent by Prometheus"
vendor = "Prometheus"
source = "https://github.com/prometheus/alertmanager"
license = "Apache-2.0"
tier = "critical"
upstream_version = "0.27.0"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/prometheus/alertmanager/releases/download/v0.27.0/alertmanager-0.27.0.linux-amd64.tar.gz"

[runtime]
entrypoint = ["/alertmanager"]

[ports]
expose = [9093, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/prometheus/alertmanager"
"org.opencontainers.image.title" = "alertmanager"
"org.opencontainers.image.vendor" = "Prometheus"
"org.opencontainers.image.version" = "0.27.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "observability"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "critical"
"evergreen.metrics.native" = "ztunnel"
