[metadata]
name = "dragonflydb"
version = "latest"
description = "dragonflydb container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "docker.dragonflydb.io/dragonfly:${VERSION}"

[runtime]
entrypoint = ["/dragonfly"]
cmd = ["--bind", "0.0.0.0:6379"]

[ports]
expose = [6379, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/dragonflydb/dragonfly"
"org.opencontainers.image.title" = "dragonflydb"
"org.opencontainers.image.vendor" = "DragonflyDB"
"org.opencontainers.image.version" = "1.38.1"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "database"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

