[metadata]
tier = "standard"
name = "couchbase-operator"
version = "2.8.0"
description = "Evergreen hardened Couchbase Operator - Kubernetes operator for Couchbase"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "ghcr.io/couchbase/couchbase-operator:v${VERSION}"

[runtime]
entrypoint = ["/usr/local/bin/couchbase-operator"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened Couchbase Operator - Kubernetes operator for Couchbase"
"org.opencontainers.image.title" = "couchbase-operator"
"org.opencontainers.image.vendor" = "Couchbase"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.image.category" = "database"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "standard""evergreen.metrics.native" = "ztunnel"
