apiVersion: v2
name: matrix-hookshot
description: "Container image — Evergreen Image Registry hardened image"
type: application
version: 0.1.0
appVersion: "latest"
maintainers:
  - name: Wyatt Au
keywords:
  - matrix-hookshot
  - security
  - hardened
  - evergreen
home: https://github.com/WyattAu/EvergreenImageRegistry/tree/main/images/matrix-hookshot
sources:
  - https://github.com/WyattAu/EvergreenImageRegistry
