[metadata]
tier = "standard"
name = "pgbouncer-exporter"
version = "0.12.0"
description = "Evergreen hardened PgBouncer Exporter - Prometheus exporter for PgBouncer"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/pgbouncer_exporter"]

[ports]
expose = [9127, 9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened PgBouncer Exporter - Prometheus exporter for PgBouncer"
"org.opencontainers.image.title" = "pgbouncer-exporter"
"org.opencontainers.image.vendor" = "Prometheus Community"
"org.opencontainers.image.version" = "0.11.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.connection-drain" = "false"
"evergreen.hft.cpu-pins" = "6-7"
"evergreen.hft.cpu-pins-mode" = "shared"
"evergreen.hft.deploy-strategy" = "standard-rolling"
"evergreen.hft.init-system" = "none"
"evergreen.hft.pre-stop-hook" = "false"
"evergreen.hft.sched-policy" = "SCHED_OTHER"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "database"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
