[metadata]
name = "whisper-cuda"
version = "20240930"
description = "whisper-cuda container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["true"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.title" = "whisper-cuda"
"org.opencontainers.image.vendor" = "OpenAI"
"org.opencontainers.image.version" = "20240930"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"


status = "wip"
