[metadata]
name = "postgis"
version = "3.4.2"
description = "postgis container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["postgres"]

[ports]
expose = [5432, 9101]

[labels]
"org.opencontainers.image.title" = "postgis"
"org.opencontainers.image.vendor" = "PostGIS"
"org.opencontainers.image.version" = "3.4.2"
"sovereign.base.image" = "wolfi"
"sovereign.constraint.hardened" = "true"
"sovereign.constraint.nonroot" = "true"
"sovereign.health.type" = "exec"
"sovereign.image.tier" = "2"
"sovereign.metrics.native" = "ztunnel"

