[metadata]
name = "thanos"
version = "0.35.0"
description = "Thanos - highly available Prometheus with long-term storage"
vendor = "Thanos"
source = "https://github.com/thanos-io/thanos"
license = "Apache-2.0"
tier = "critical"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/thanos-io/thanos/releases/download/v0.35.0/thanos-0.35.0.linux-amd64.tar.gz"

[runtime]
entrypoint = ["/thanos"]

[ports]
expose = [10902, 9101]

[labels]
"org.opencontainers.image.title" = "thanos"
"org.opencontainers.image.vendor" = "Thanos"
"org.opencontainers.image.version" = "0.35.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.connection-drain" = "true"
"evergreen.hft.cpu-pins" = "4-5"
"evergreen.hft.cpu-pins-mode" = "exclusive"
"evergreen.hft.deploy-strategy" = "hft-stateful"
"evergreen.hft.init-system" = "none"
"evergreen.hft.pre-stop-delay" = "5s"
"evergreen.hft.pre-stop-hook" = "true"
"evergreen.hft.sched-policy" = "SCHED_OTHER"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "critical"
"evergreen.metrics.native" = "ztunnel"
