[metadata]
name = "drone"
version = "2.28.1"
description = "Drone - cloud-native continuous integration and delivery platform"
vendor = "Harness"
source = "https://github.com/harness/drone"
license = "Apache-2.0"
tier = "1"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/drone/drone/releases/download/v2.28.1/drone-2.28.1-linux-amd64.tar.gz"

[runtime]
entrypoint = ["/drone"]

[ports]
expose = [80, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/drone/drone"
"org.opencontainers.image.title" = "drone"
"org.opencontainers.image.vendor" = "Drone"
"org.opencontainers.image.version" = "2.28.1"
"sovereign.base.image" = "scratch"
"sovereign.constraint.nonroot" = "true"
"sovereign.constraint.scratch" = "true"
"sovereign.health.type" = "exec"
"sovereign.image.tier" = "2"
"sovereign.metrics.native" = "ztunnel"

