[metadata]
name = "ollama-rocm"
version = "0.5.7"
description = "ollama-rocm container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["true"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.title" = "ollama-rocm"
"org.opencontainers.image.vendor" = "Ollama"
"org.opencontainers.image.version" = "0.5.7"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"

