[metadata]
name = "authelia"
version = "4.39.19"
description = "Authelia - single sign-on and two-factor authentication portal"
vendor = "Authelia"
source = "https://github.com/authelia/authelia"
license = "Apache-2.0"
tier = "2"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/authelia/authelia/releases/download/v4.39.19/authelia-4.39.19-linux-amd64.tar.gz"

[runtime]
entrypoint = ["/authelia"]

[ports]
expose = [80, 9101]

[labels]
"org.opencontainers.image.title" = "authelia"
"org.opencontainers.image.vendor" = "Authelia"
"org.opencontainers.image.version" = "4.39.19"
"sovereign.base.image" = "scratch"
"sovereign.constraint.nonroot" = "true"
"sovereign.constraint.scratch" = "true"
"sovereign.health.type" = "exec"
"sovereign.hft.init-system" = "none"
"sovereign.hft.shutdown-timeout" = "3s"
"sovereign.hft.signal-handling" = "native"
"sovereign.hft.startup-timeout" = "3000ms"
"sovereign.image.tier" = "1"
"sovereign.metrics.native" = "ztunnel"

