[metadata]
tier = "standard"
name = "flux"
version = "2.3.0"
description = "flux container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/flux"]

[ports]
expose = [3030, 9101]

[labels]
"org.opencontainers.image.title" = "flux"
"org.opencontainers.image.vendor" = "Flux"
"org.opencontainers.image.version" = "2.3.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
