[metadata]
tier = "standard"
name = "lynis"
version = "unknown"
description = "Lynis - Security auditing tool"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/app/src/lynis"]
cmd = ["audit", "system"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.description" = "Lynis - Security auditing tool"
"org.opencontainers.image.source" = "https://github.com/CISOfy/Lynis"
"org.opencontainers.image.title" = "lynis"
"org.opencontainers.image.vendor" = "CISOfy"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "standard""evergreen.metrics.native" = "ztunnel"
