[metadata]
tier = "standard"
name = "transformers-gpu"
version = "4.46.0"
description = "transformers-gpu container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["python3"]

[ports]
expose = [8000, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/huggingface/transformers"
"org.opencontainers.image.title" = "transformers-gpu"
"org.opencontainers.image.vendor" = "HuggingFace"
"org.opencontainers.image.version" = "4.46.0"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"

