[metadata]
name = "dovecot"
version = "2.3.21"
description = "dovecot container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["dovecot"]
cmd = ["-F"]

[ports]
expose = [143, 9101]

[labels]
"evergreen.base.image" = "wolfi"
"evergreen.health.type" = "exec"
"evergreen.metrics.native" = "ztunnel"

