[metadata]
name = "traefik"
version = "3.6.14"
description = "Traefik - modern HTTP reverse proxy and load balancer"
vendor = "Traefik Labs"
source = "https://github.com/traefik/traefik"
license = "MIT"
tier = "1"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/traefik/traefik/releases/download/v3.6.14/traefik-3.6.14-linux-amd64.tar.gz"

[runtime]
entrypoint = ["/traefik"]

[ports]
expose = [80, 9101]

[labels]
"org.opencontainers.image.title" = "traefik"
"org.opencontainers.image.vendor" = "Traefik Labs"
"org.opencontainers.image.version" = "3.6.13"
"sovereign.base.image" = "scratch"
"sovereign.constraint.nonroot" = "true"
"sovereign.constraint.scratch" = "true"
"sovereign.health.type" = "exec"
"sovereign.hft.connection-drain" = "true"
"sovereign.hft.cpu-pins" = "0-1"
"sovereign.hft.cpu-pins-mode" = "exclusive"
"sovereign.hft.deploy-strategy" = "hft-rolling"
"sovereign.hft.init-system" = "none"
"sovereign.hft.pre-stop-delay" = "5s"
"sovereign.hft.pre-stop-hook" = "true"
"sovereign.hft.shutdown-timeout" = "3s"
"sovereign.hft.signal-handling" = "native"
"sovereign.hft.startup-timeout" = "3000ms"
"sovereign.hft.xdp-capable" = "false"
"sovereign.hft.xdp-notes" = "Not supported; use envoy for XDP workloads"
"sovereign.image.tier" = "1"
"sovereign.metrics.native" = "ztunnel"

