[metadata]
tier = "standard"
name = "yarr"
version = "2.4.0"
description = "yarr container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "debian:bookworm-slim"

[runtime]
entrypoint = ["/yarr"]

[ports]
expose = [7070, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/nickvdyck/yarr"
"org.opencontainers.image.title" = "yarr"
"org.opencontainers.image.vendor" = "yarr"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"

