[metadata]
name = "meilisearch"
version = "1.42.1"
description = "Meilisearch - fast, relevant, and typo-tolerant search engine"
vendor = "Meilisearch"
source = "https://github.com/meilisearch/meilisearch"
license = "Apache-2.0"
tier = "standard"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/meilisearch/meilisearch/releases/download/v1.42.1/meilisearch-1.42.1-linux-amd64.tar.gz"

[runtime]
entrypoint = ["/meilisearch"]

[ports]
expose = [7700, 9101]

[labels]
"org.opencontainers.image.title" = "meilisearch"
"org.opencontainers.image.vendor" = "Meilisearch"
"org.opencontainers.image.version" = "1.42.1"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

