[metadata]
name = "unoconv"
version = "0.8"
description = "unoconv container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["unoconv"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/dagwieers/unoconv"
"org.opencontainers.image.title" = "unoconv"
"org.opencontainers.image.vendor" = "Unoconv"
"org.opencontainers.image.version" = "0.8"
"sovereign.base.image" = "wolfi"
"sovereign.constraint.base" = "wolfi"
"sovereign.constraint.nonroot" = "true"
"sovereign.health.type" = "exec"
"sovereign.hft.init-system" = "none"
"sovereign.hft.shutdown-timeout" = "10s"
"sovereign.hft.signal-handling" = "native"
"sovereign.hft.startup-timeout" = "30000ms"
"sovereign.image.category" = "document-management"
"sovereign.image.status" = "functional"
"sovereign.image.tier" = "2"
"sovereign.metrics.native" = "ztunnel"

