[metadata]
name = "egroupware"
version = "23.1.20240608"
description = "egroupware container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["php-fpm8.4"]

[ports]
expose = [80, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/EGroupware/egroupware"
"org.opencontainers.image.title" = "egroupware"
"org.opencontainers.image.vendor" = "EGroupware"
"org.opencontainers.image.version" = "23.1.20240608"
"sovereign.base.image" = "wolfi"
"sovereign.constraint.base" = "wolfi"
"sovereign.constraint.nonroot" = "true"
"sovereign.health.type" = "exec"
"sovereign.hft.init-system" = "none"
"sovereign.hft.shutdown-timeout" = "10s"
"sovereign.hft.signal-handling" = "native"
"sovereign.hft.startup-timeout" = "30000ms"
"sovereign.image.category" = "project-management"
"sovereign.image.status" = "functional"
"sovereign.image.tier" = "2"
"sovereign.metrics.native" = "ztunnel"

