[metadata]
name = "tasmota"
version = "unknown"
description = "tasmota container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
cmd = ["-c", "print('Tasmota firmware build environment. Clone https://github.com/arendst/Tasmota and run platformio.')"]

[ports]
expose = [9101]

[labels]
"evergreen.base.image" = "wolfi"
"evergreen.health.type" = "exec"
"evergreen.metrics.native" = "ztunnel"

