[metadata]
name = "convector"
version = "1.0.0"
description = "Convector - smart contract framework tools"
vendor = "worldsibu"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/worldsibu/convector-platform/releases/download/v1.0.0/convector-server-linux-amd64.tar.gz"

[runtime]
entrypoint = ["node"]

[ports]
expose = [8008, 9101]

[labels]
"org.opencontainers.image.description" = "Convector - smart contract framework tools"
"org.opencontainers.image.source" = "https://github.com/worldsibu/convector-platform"
"org.opencontainers.image.title" = "convector"
"org.opencontainers.image.vendor" = "worldsibu"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "tcp"
"evergreen.image.category" = "blockchain"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"

