apiVersion: v2
name: cockroachdb
description: "Container image — Evergreen Image Registry hardened image"
type: application
version: 0.1.0
appVersion: "latest"
maintainers:
  - name: Wyatt Au
keywords:
  - cockroachdb
  - security
  - hardened
  - evergreen
home: https://github.com/WyattAu/EvergreenImageRegistry/tree/main/images/cockroachdb
sources:
  - https://github.com/WyattAu/EvergreenImageRegistry
