[metadata]
tier = "standard"
name = "openproject"
version = "14.0.5"
description = "openproject container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/openproject/openproject"
[runtime]
entrypoint = ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]

[ports]
expose = [3000, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/opf/openproject"
"org.opencontainers.image.title" = "openproject"
"org.opencontainers.image.vendor" = "OpenProject"
"org.opencontainers.image.version" = "14.0.5"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.base" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "10s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "60000ms"
"evergreen.image.category" = "project-management"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
