[metadata]
name = "netmaker"
version = "1.5.1"
description = "netmaker container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/netmaker"]

[ports]
expose = [443, 9101]

[labels]
"org.opencontainers.image.title" = "netmaker"
"org.opencontainers.image.vendor" = "NetMaker"
"org.opencontainers.image.version" = "1.5.1"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

