//go:build !ignore_autogenerated

// =============================================================================
// DeepCopy generated methods
// =============================================================================
// These are normally generated by kubebuilder code-gen.
// Required for runtime.Object interface implementation.
// =============================================================================

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvergreenImage) DeepCopyInto(out *EvergreenImage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvergreenImage.
func (in *EvergreenImage) DeepCopy() *EvergreenImage {
	if in == nil {
		return nil
	}
	out := new(EvergreenImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvergreenImage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvergreenImageList) DeepCopyInto(out *EvergreenImageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EvergreenImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvergreenImageList.
func (in *EvergreenImageList) DeepCopy() *EvergreenImageList {
	if in == nil {
		return nil
	}
	out := new(EvergreenImageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvergreenImageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvergreenImageSpec) DeepCopyInto(out *EvergreenImageSpec) {
	*out = *in
	out.Compliance = in.Compliance
	out.Notifications = in.Notifications
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvergreenImageSpec.
func (in *EvergreenImageSpec) DeepCopy() *EvergreenImageSpec {
	if in == nil {
		return nil
	}
	out := new(EvergreenImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvergreenImageStatus) DeepCopyInto(out *EvergreenImageStatus) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvergreenImageStatus.
func (in *EvergreenImageStatus) DeepCopy() *EvergreenImageStatus {
	if in == nil {
		return nil
	}
	out := new(EvergreenImageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceSpec) DeepCopyInto(out *ComplianceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceSpec.
func (in *ComplianceSpec) DeepCopy() *ComplianceSpec {
	if in == nil {
		return nil
	}
	out := new(ComplianceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationsSpec) DeepCopyInto(out *NotificationsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationsSpec.
func (in *NotificationsSpec) DeepCopy() *NotificationsSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvergreenPolicy) DeepCopyInto(out *EvergreenPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvergreenPolicy.
func (in *EvergreenPolicy) DeepCopy() *EvergreenPolicy {
	if in == nil {
		return nil
	}
	out := new(EvergreenPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvergreenPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvergreenPolicyList) DeepCopyInto(out *EvergreenPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EvergreenPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvergreenPolicyList.
func (in *EvergreenPolicyList) DeepCopy() *EvergreenPolicyList {
	if in == nil {
		return nil
	}
	out := new(EvergreenPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvergreenPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvergreenPolicySpec) DeepCopyInto(out *EvergreenPolicySpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]PolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Exemptions != nil {
		in, out := &in.Exemptions, &out.Exemptions
		*out = make([]PolicyExemption, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvergreenPolicySpec.
func (in *EvergreenPolicySpec) DeepCopy() *EvergreenPolicySpec {
	if in == nil {
		return nil
	}
	out := new(EvergreenPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvergreenPolicyStatus) DeepCopyInto(out *EvergreenPolicyStatus) {
	*out = *in
	if in.LastEvaluated != nil {
		in, out := &in.LastEvaluated, &out.LastEvaluated
		*out = (*in).DeepCopy()
	}
	if in.ViolationDetails != nil {
		in, out := &in.ViolationDetails, &out.ViolationDetails
		*out = make([]PolicyViolation, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvergreenPolicyStatus.
func (in *EvergreenPolicyStatus) DeepCopy() *EvergreenPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(EvergreenPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRule) DeepCopyInto(out *PolicyRule) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRule.
func (in *PolicyRule) DeepCopy() *PolicyRule {
	if in == nil {
		return nil
	}
	out := new(PolicyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyExemption) DeepCopyInto(out *PolicyExemption) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyExemption.
func (in *PolicyExemption) DeepCopy() *PolicyExemption {
	if in == nil {
		return nil
	}
	out := new(PolicyExemption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvergreenDrift) DeepCopyInto(out *EvergreenDrift) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvergreenDrift.
func (in *EvergreenDrift) DeepCopy() *EvergreenDrift {
	if in == nil {
		return nil
	}
	out := new(EvergreenDrift)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvergreenDrift) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvergreenDriftList) DeepCopyInto(out *EvergreenDriftList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EvergreenDrift, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvergreenDriftList.
func (in *EvergreenDriftList) DeepCopy() *EvergreenDriftList {
	if in == nil {
		return nil
	}
	out := new(EvergreenDriftList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvergreenDriftList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvergreenDriftSpec) DeepCopyInto(out *EvergreenDriftSpec) {
	*out = *in
	out.Alerting = in.Alerting
	out.Thresholds = in.Thresholds
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvergreenDriftSpec.
func (in *EvergreenDriftSpec) DeepCopy() *EvergreenDriftSpec {
	if in == nil {
		return nil
	}
	out := new(EvergreenDriftSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvergreenDriftStatus) DeepCopyInto(out *EvergreenDriftStatus) {
	*out = *in
	if in.LastCheck != nil {
		in, out := &in.LastCheck, &out.LastCheck
		*out = (*in).DeepCopy()
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvergreenDriftStatus.
func (in *EvergreenDriftStatus) DeepCopy() *EvergreenDriftStatus {
	if in == nil {
		return nil
	}
	out := new(EvergreenDriftStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertingSpec) DeepCopyInto(out *AlertingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertingSpec.
func (in *AlertingSpec) DeepCopy() *AlertingSpec {
	if in == nil {
		return nil
	}
	out := new(AlertingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftThresholds) DeepCopyInto(out *DriftThresholds) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftThresholds.
func (in *DriftThresholds) DeepCopy() *DriftThresholds {
	if in == nil {
		return nil
	}
	out := new(DriftThresholds)
	in.DeepCopyInto(out)
	return out
}

// Suppress unused import warning
var _ = runtime.Object(nil)
