[metadata]
name = "eqonomize"
version = "0.10.1"
description = "eqonomize container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["eqonomize"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/Eqonomize/Eqonomize"
"org.opencontainers.image.title" = "eqonomize"
"org.opencontainers.image.vendor" = "Eqonomize"
"org.opencontainers.image.version" = "0.10.1"
"sovereign.base.image" = "wolfi"
"sovereign.constraint.base" = "wolfi"
"sovereign.constraint.nonroot" = "true"
"sovereign.health.type" = "exec"
"sovereign.hft.init-system" = "none"
"sovereign.hft.shutdown-timeout" = "5s"
"sovereign.hft.signal-handling" = "native"
"sovereign.hft.startup-timeout" = "10000ms"
"sovereign.image.category" = "business-finance"
"sovereign.image.status" = "functional"
"sovereign.image.tier" = "2"
"sovereign.metrics.native" = "ztunnel"

