[metadata]
tier = "standard"
name = "postgresql-14"
version = "14.23"
description = "postgresql-14 container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["postgres"]

[ports]
expose = [5432, 9101]

[labels]
"org.opencontainers.image.title" = "postgresql-14"
"org.opencontainers.image.vendor" = "PostgreSQL"
"org.opencontainers.image.version" = "14.13"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.hardened" = "true"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"
