#!/bin/bash
set -euo pipefail

OUTDATED_FILE="${1:?Usage: bump_all_outdated.sh <outdated-file> [commit-message-prefix]}"
COMMIT_PREFIX="${2:-chore: auto-bump}"

REPO_ROOT="$(git rev-parse --show-toplevel)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUMP_SCRIPT="${SCRIPT_DIR}/bump_versions.sh"

if [ ! -f "$OUTDATED_FILE" ]; then
    echo "ERROR: Outdated file not found: ${OUTDATED_FILE}" >&2
    exit 1
fi

TOTAL=0
BUMPED=0
FAILED=0
CHANGES=""

while IFS= read -r line; do
    [[ "$line" =~ ^IMAGE ]] && continue
    [[ "$line" =~ ^-+ ]] && continue
    [[ "$line" =~ ^$ ]] && continue
    [[ "$line" =~ Summary ]] && continue
    [[ "$line" =~ Hint ]] && continue

    IMAGE_NAME=$(echo "$line" | awk '{print $1}')
    CURRENT=$(echo "$line" | awk '{print $2}')
    LATEST=$(echo "$line" | awk '{print $3}')
    STATUS=$(echo "$line" | awk '{print $4}')

    [[ "$STATUS" != "OUTDATED" ]] && continue
    [[ -z "$LATEST" || "$LATEST" == "-" || "$LATEST" == "ERROR"* ]] && continue

    TOTAL=$((TOTAL + 1))
    echo "Processing: ${IMAGE_NAME} (${CURRENT} -> ${LATEST})"

    if bash "$BUMP_SCRIPT" "$IMAGE_NAME" "$LATEST"; then
        BUMPED=$((BUMPED + 1))
        CHANGES="${CHANGES}  - ${IMAGE_NAME}: ${CURRENT} -> ${LATEST}\n"
    else
        FAILED=$((FAILED + 1))
        echo "  WARNING: Failed to bump ${IMAGE_NAME}"
    fi
done < "$OUTDATED_FILE"

echo ""
echo "Results: ${BUMPED} bumped, ${FAILED} failed, ${TOTAL} total outdated"

if [ "$BUMPED" -gt 0 ]; then
    BODY=$(printf 'Automated version bumps:\n\n%s\nGenerated by bump_all_outdated.sh' "$CHANGES")
    if [ -n "$(git -C "$REPO_ROOT" status --porcelain)" ]; then
        git -C "$REPO_ROOT" add -A
        git -C "$REPO_ROOT" commit -m "${COMMIT_PREFIX}: update ${BUMPED} image versions

$(echo -e "$BODY")"
        echo "Committed ${BUMPED} version bumps"
    else
        echo "No changes to commit"
    fi
fi

exit $FAILED
