[metadata]
name = "step-acme"
version = "0.30.2"
description = "step-acme container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/step-ca"]
cmd = ["--acme"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/smallstep/certificates"
"org.opencontainers.image.title" = "step-acme"
"org.opencontainers.image.vendor" = "Smallstep"
"org.opencontainers.image.version" = "0.30.2"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "security"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"

