[metadata]
name = "nxlog"
version = "latest"
description = "NXLog Community Edition - log collection and forwarding"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "nxlog/nxlog:${VERSION}"

[runtime]
entrypoint = ["/opt/nxlog/bin/nxlog"]
cmd = ["-c", "/app/conf/nxlog.conf"]

[ports]
expose = [514, 9101]

[labels]
"org.opencontainers.image.description" = "NXLog Community Edition - log collection and forwarding"
"org.opencontainers.image.title" = "nxlog"
"org.opencontainers.image.vendor" = "nxlog"
"org.opencontainers.image.version" = "3.1.2331"
"sovereign.base.image" = "wolfi"
"sovereign.constraint.nonroot" = "true"
"sovereign.health.type" = "exec"
"sovereign.hft.connection-drain" = "true"
"sovereign.hft.cpu-pins" = "4-5"
"sovereign.hft.cpu-pins-mode" = "shared"
"sovereign.hft.deploy-strategy" = "standard-rolling"
"sovereign.hft.init-system" = "none"
"sovereign.hft.pre-stop-delay" = "5s"
"sovereign.hft.pre-stop-hook" = "true"
"sovereign.hft.runtime" = "c"
"sovereign.hft.sched-policy" = "SCHED_OTHER"
"sovereign.hft.shutdown-timeout" = "5s"
"sovereign.hft.signal-handling" = "native"
"sovereign.hft.startup-timeout" = "5000ms"
"sovereign.image.tier" = "1"
"sovereign.metrics.native" = "ztunnel"

