[metadata]
name = "wireguard"
version = "0.0.20230223"
description = "WireGuard - fast, modern, secure VPN tunnel"
vendor = "WireGuard"
source = "https://github.com/WireGuard/wireguard-go"
license = "Apache-2.0"
tier = "3"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/wireguard/wireguard/releases/download/v0.0.20230223/wireguard-0.0.20230223-linux-amd64.tar.gz"

[runtime]
entrypoint = ["/wireguard-go"]
cmd = ["-f", "wg0"]

[ports]
expose = ["51820/udp", 9101]

[labels]
"org.opencontainers.image.source" = "https://git.zx2c4.com/wireguard-go"
"org.opencontainers.image.title" = "wireguard"
"org.opencontainers.image.vendor" = "WireGuard"
"org.opencontainers.image.version" = "0.0.20230223"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "networking"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

