[metadata]
tier = "standard"
name = "keycloak-quarkus"
version = "26.6.1"
description = "keycloak-quarkus container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/opt/keycloak/bin/kc.sh"]
cmd = ["start-dev"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/keycloak/keycloak"
"org.opencontainers.image.title" = "keycloak-quarkus"
"org.opencontainers.image.vendor" = "Keycloak"
"org.opencontainers.image.version" = "26.6.1"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.base" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "30s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "60000ms"
"evergreen.image.category" = "identity"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"
