[metadata]
name = "kubescape"
version = "4.0.5"
description = "Kubescape - Kubernetes security platform"
vendor = "Kubescape"
source = "https://github.com/kubescape/kubescape"
license = "Apache-2.0"
tier = "standard"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/kubescape/kubescape/releases/download/v4.0.5/kubescape-ubuntu-amd64"

[runtime]
entrypoint = ["/kubescape"]
cmd = ["--help"]

[ports]
expose = [9101]

[labels]
"evergreen.base.image" = "scratch"
"evergreen.health.type" = "exec"
"evergreen.metrics.native" = "ztunnel"
