[metadata]
name = "zfs-exporter"
version = "0.5.3"
description = "ZFS statistics exporter for Prometheus"
vendor = "frebib"
source = "https://github.com/frebib/zfs-exporter"
license = "MIT"
tier = "critical"
upstream_version = "0.5.3"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "source-build"
url = "https://github.com/frebib/zfs-exporter"

[runtime]
entrypoint = ["/usr/local/bin/shim", "run", "-c", "/usr/local/bin/zfs-exporter"]

[ports]
expose = [9134, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/frebib/zfs-exporter"
"org.opencontainers.image.title" = "zfs-exporter"
"org.opencontainers.image.vendor" = "frebib"
"org.opencontainers.image.version" = "0.5.3"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "http"
"evergreen.image.category" = "monitoring"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "critical"
