[metadata]
name = "conduit-admin"
version = "0.4.0"
description = "Conduit Admin - Conduit Matrix homeserver with admin utilities"
vendor = "Famedly"
source = "https://gitlab.com/famedly/conduit"
tier = "standard"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://gitlab.com/api/v4/projects/famedly%2Fconduit/packages/generic/conduit-v0.9.x/v0.9.5/conduit-x86_64-unknown-linux-musl"

[runtime]
entrypoint = ["/usr/local/bin/conduit"]

[ports]
expose = [6167, 9101]

[labels]
"org.opencontainers.image.description" = "Conduit Admin - Conduit Matrix homeserver with admin utilities"
"org.opencontainers.image.source" = "https://gitlab.com/famedly/conduit"
"org.opencontainers.image.title" = "conduit-admin"
"org.opencontainers.image.vendor" = "Famedly"
"org.opencontainers.image.version" = "0.9.5"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"

