[metadata]
tier = "standard"
name = "gallery3"
version = "3.0.0"
description = "gallery3 container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["python3", "/opt/gallery3/manage.py", "runserver", "0.0.0.0:8000"]

[ports]
expose = [8000, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/gallery/gallery3.git"
"org.opencontainers.image.title" = "gallery3"
"org.opencontainers.image.vendor" = "Gallery"
"org.opencontainers.image.version" = "3.0.0"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"
