[metadata]
tier = "standard"
name = "sonarr-develop"
version = "4.0.17.2953"
description = "sonarr-develop container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/app/Sonarr"]

[ports]
expose = [8989, 9101]

[labels]
"org.opencontainers.image.title" = "sonarr-develop"
"evergreen.health.type" = "exec"
"evergreen.metrics.native" = "ztunnel"
