[metadata]
tier = "standard"
name = "spamassassin"
version = "4.0.0"
description = "spamassassin container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/devent/spamassassin"
[runtime]
entrypoint = ["spamassassin"]
cmd = ["-d"]

[ports]
expose = [783, 9101]

[labels]
"evergreen.base.image" = "wolfi"
"evergreen.health.type" = "exec"
"evergreen.metrics.native" = "ztunnel"
