[metadata]
tier = "standard"
name = "chevereto"
version = "4.1.0"
description = "chevereto container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["php"]

[ports]
expose = [80, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/Chevereto/Chevereto/releases"
"org.opencontainers.image.title" = "chevereto"
"org.opencontainers.image.vendor" = "Chevereto/Chevereto"
"org.opencontainers.image.version" = "4.1.0"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"

