[metadata]
name = "open-webui"
version = "0.6.4"
description = "open-webui container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["node"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/open-webui/open-webui/releases"
"org.opencontainers.image.title" = "open-webui"
"org.opencontainers.image.vendor" = "open-webui/open-webui"
"org.opencontainers.image.version" = "0.6.4"
"sovereign.base.image" = "wolfi"
"sovereign.constraint.hardened" = "true"
"sovereign.constraint.nonroot" = "true"
"sovereign.health.type" = "exec"
"sovereign.image.tier" = "3"
"sovereign.metrics.native" = "ztunnel"

