[metadata]
tier = "standard"
name = "sbt"
version = "1.12.10"
description = "Evergreen hardened sbt - Scala build tool"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/sbtscala/scala-sbt"
[runtime]
entrypoint = ["sbt"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened sbt - Scala build tool"
"org.opencontainers.image.title" = "sbt"
"org.opencontainers.image.vendor" = "Scala"
"org.opencontainers.image.version" = "1.12.10"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.shutdown-timeout" = "30s"
"evergreen.hft.signal-handling" = "native"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
