[metadata]
tier = "standard"
name = "node"
version = "20.12.2"
description = "node container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["node"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.title" = "node"
"org.opencontainers.image.vendor" = "Node.js"
"org.opencontainers.image.version" = "20.12.2"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.hardened" = "true"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
