[metadata]
tier = "standard"
name = "wandb-server"
version = "0.19.0"
description = "wandb-server container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/wandb/local"
[runtime]
entrypoint = ["wandb"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/wandb/server"
"org.opencontainers.image.title" = "wandb-server"
"org.opencontainers.image.vendor" = "Weights & Biases"
"org.opencontainers.image.version" = "0.19.0"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
