[metadata]
name = "consul-template"
version = "0.37.0"
description = "Consul Template - template rendering with Consul data"
vendor = "HashiCorp"
source = "https://github.com/hashicorp/consul-template"
license = "Apache-2.0"
tier = "standard"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/consul-template/consul-template/releases/download/v0.37.0/consul-template-0.37.0-linux-amd64.tar.gz"

[runtime]
entrypoint = ["/consul-template"]

[ports]
expose = [8500, 9101]

[labels]
"org.opencontainers.image.title" = "consul-template"
"org.opencontainers.image.vendor" = "HashiCorp"
"org.opencontainers.image.version" = "0.37.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.cap-drop" = "ALL"
"evergreen.hft.cap-required" = "CAP_SYS_NICE"
"evergreen.hft.fips-required" = "true"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "5s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "5000ms"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

