[metadata]
name = "vaultwarden"
version = "1.35.7"
description = "Vaultwarden - lightweight Bitwarden-compatible password manager"
vendor = "dani-garcia"
source = "https://github.com/dani-garcia/vaultwarden"
license = "Apache-2.0"
tier = "2"
upstream_version = "1.35.7"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "vaultwarden/server:1.35.7"

[runtime]
entrypoint = ["/vaultwarden"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/dani-garcia/vaultwarden"
"org.opencontainers.image.title" = "vaultwarden"
"org.opencontainers.image.vendor" = "dani-garcia"
"org.opencontainers.image.version" = "1.35.7"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "secrets"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"
