[metadata]
tier = "standard"
name = "healthcheck"
version = "0.4.36"
description = "grpc-health-probe - gRPC health checking tool for Kubernetes"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/grpc_health_probe"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.description" = "grpc-health-probe - gRPC health checking tool for Kubernetes"
"org.opencontainers.image.title" = "healthcheck"
"org.opencontainers.image.vendor" = "grpc-ecosystem"
"org.opencontainers.image.version" = "0.4.36"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.connection-drain" = "false"
"evergreen.hft.cpu-pins" = "6-7"
"evergreen.hft.cpu-pins-mode" = "shared"
"evergreen.hft.deploy-strategy" = "standard-rolling"
"evergreen.hft.init-system" = "none"
"evergreen.hft.pre-stop-hook" = "false"
"evergreen.hft.runtime" = "go"
"evergreen.hft.sched-policy" = "SCHED_OTHER"
"evergreen.hft.shutdown-timeout" = "2s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "1000ms"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"
