[metadata]
name = "planka"
version = "1.17.0"
description = "planka container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "planka"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["node"]

[ports]
expose = [3000, 9101]

[labels]
"org.opencontainers.image.title" = "planka"
"org.opencontainers.image.vendor" = "Planka"
"org.opencontainers.image.version" = "1.17.0"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"

