[metadata]
tier = "standard"
name = "netmaker-ui"
version = "v1.5.1"
description = "netmaker-ui container image"

[build]
base = "gcr.io/distroless/static-debian12@sha256:20bc6c0bc4d625a22a8fde3e55f6515709b32055ef8fb9cfbddaa06d1760f838"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "gravitl/netmaker-ui:v1.5.1"

[runtime]
entrypoint = ["sleep", "infinity"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/gravitl/netmaker-ui"
"org.opencontainers.image.title" = "netmaker-ui"
"org.opencontainers.image.vendor" = "Gravitl"
"org.opencontainers.image.version" = "v1.5.1"
"evergreen.base.image" = "distroless"
"evergreen.constraint.distrole" = "distroless"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "networking"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"
