[metadata]
tier = "standard"
name = "portainer-edge"
version = "latest"
description = "Portainer Edge Agent"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "portainer/agent:${VERSION}"

[runtime]
entrypoint = ["/portainer-edge-agent"]
cmd = ["--help"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.description" = "Portainer Edge Agent"
"org.opencontainers.image.source" = "https://github.com/portainer/agent"
"org.opencontainers.image.title" = "portainer-edge"
"org.opencontainers.image.vendor" = "Portainer"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"

