[metadata]
name = "wireguard-ui"
version = "0.5.4"
description = "wireguard-ui container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/wireguard-ui"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/ngoduykhanh/wireguard-ui"
"org.opencontainers.image.title" = "wireguard-ui"
"org.opencontainers.image.vendor" = "ngoduykhanh"
"org.opencontainers.image.version" = "0.5.4"
"sovereign.base.image" = "scratch"
"sovereign.constraint.nonroot" = "true"
"sovereign.constraint.scratch" = "true"
"sovereign.health.type" = "exec"
"sovereign.hft.init-system" = "none"
"sovereign.hft.shutdown-timeout" = "3s"
"sovereign.hft.signal-handling" = "native"
"sovereign.hft.startup-timeout" = "3000ms"
"sovereign.image.category" = "networking"
"sovereign.image.status" = "functional"
"sovereign.image.tier" = "1"
"sovereign.metrics.native" = "ztunnel"

