[metadata]
tier = "standard"
name = "koel-next"
version = "6.10.3"
description = "koel-next container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["php"]

[ports]
expose = [80, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/koel/koel/releases"
"org.opencontainers.image.title" = "koel-next"
"org.opencontainers.image.vendor" = "koel/koel"
"org.opencontainers.image.version" = "6.10.3"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "3"
"evergreen.metrics.native" = "ztunnel"
