[metadata]
tier = "standard"
name = "apache-ofbiz"
version = "24.09.05"
description = "apache-ofbiz container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["java", "-jar", "/opt/apache-ofbiz/apache-ofbiz"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/apache/ofbiz-framework"
"org.opencontainers.image.title" = "apache-ofbiz"
"org.opencontainers.image.vendor" = "Apache OFBiz"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.base" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "30s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "60000ms"
"evergreen.image.category" = "crm-erp"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
