[metadata]
tier = "standard"
name = "rabbitmq-amqp"
version = "3.13.1"
description = "Evergreen hardened RabbitMQ with AMQP 1.0 plugin"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["rabbitmq-server"]

[ports]
expose = [5672, 9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened RabbitMQ with AMQP 1.0 plugin"
"org.opencontainers.image.title" = "rabbitmq-amqp"
"org.opencontainers.image.vendor" = "RabbitMQ"
"org.opencontainers.image.version" = "3.13.1"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.category" = "messaging"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

