[metadata]
name = "vault"
version = "1.18.1"
description = "Vault - secrets management and data protection by HashiCorp"
vendor = "HashiCorp"
source = "https://github.com/hashicorp/vault"
license = "MPL-2.0"
tier = "1"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://releases.hashicorp.com/vault/1.18.1/vault_1.18.1_linux_amd64.zip"

[runtime]
entrypoint = ["/vault"]

[ports]
expose = [8200, 9101]

[labels]
"org.opencontainers.image.title" = "vault"
"org.opencontainers.image.vendor" = "HashiCorp"
"org.opencontainers.image.version" = "1.18.1"
"sovereign.base.image" = "scratch"
"sovereign.constraint.nonroot" = "true"
"sovereign.constraint.scratch" = "true"
"sovereign.health.type" = "exec"
"sovereign.hft.cap-drop" = "ALL"
"sovereign.hft.cap-required" = "CAP_SYS_NICE"
"sovereign.hft.fips-required" = "true"
"sovereign.hft.init-system" = "none"
"sovereign.hft.shutdown-timeout" = "5s"
"sovereign.hft.signal-handling" = "native"
"sovereign.hft.startup-timeout" = "5000ms"
"sovereign.image.tier" = "1"
"sovereign.metrics.native" = "ztunnel"

