[metadata]
name = "helm"
version = "3.15.1"
description = "Helm - package manager for Kubernetes"
vendor = "Helm"
source = "https://github.com/helm/helm"
license = "Apache-2.0"
tier = "standard"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://get.helm.sh/helm-v3.15.1-linux-amd64.tar.gz"

[runtime]
entrypoint = ["/helm"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.title" = "helm"
"org.opencontainers.image.vendor" = "Helm"
"org.opencontainers.image.version" = "3.15.1"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
