[metadata]
tier = "standard"
name = "valkey-cluster"
version = "8.0.1"
description = "Valkey in Cluster Mode - Distributed Key-Value Store"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "valkey/valkey:${VERSION}"

[ports]
expose = [6379, 9101]

[labels]
"org.opencontainers.image.description" = "Valkey in Cluster Mode - Distributed Key-Value Store"
"org.opencontainers.image.source" = "https://github.com/valkey-io/valkey"
"org.opencontainers.image.title" = "valkey-cluster"
"org.opencontainers.image.vendor" = "Valkey"
"org.opencontainers.image.version" = "7.2.4"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

