[metadata]
name = "kube-state-metrics"
version = "2.18.0"
description = "Kube-state-metrics - metrics about Kubernetes objects"
vendor = "Kubernetes"
source = "https://github.com/kubernetes/kube-state-metrics"
license = "Apache-2.0"
tier = "standard"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/kube-state-metrics/kube-state-metrics/releases/download/v2.18.0/kube-state-metrics-2.18.0-linux-amd64.tar.gz"

[runtime]
entrypoint = ["/kube-state-metrics"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.title" = "kube-state-metrics"
"org.opencontainers.image.vendor" = "Kubernetes"
"org.opencontainers.image.version" = "2.18.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "standard""evergreen.metrics.native" = "ztunnel"
