[metadata]
tier = "standard"
name = "libreoffice-headless"
version = "24.8.2"
description = "libreoffice-headless container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["libreoffice"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.source" = "https://www.libreoffice.org/"
"org.opencontainers.image.title" = "libreoffice-headless"
"org.opencontainers.image.vendor" = "LibreOffice"
"org.opencontainers.image.version" = "24.8.2"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.base" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "10s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "30000ms"
"evergreen.image.category" = "document-management"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"
