[metadata]
name = "headscale"
version = "0.16.0"
description = "Headscale - open source implementation of the Tailscale control server"
vendor = "Headscale"
source = "https://github.com/juanfont/headscale"
license = "Apache-2.0"
tier = "3"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/headscale/headscale/releases/download/v0.16.0/headscale-0.16.0-linux-amd64.tar.gz"

[runtime]
entrypoint = ["/headscale"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.title" = "headscale"
"org.opencontainers.image.vendor" = "Headscale"
"org.opencontainers.image.version" = "0.16.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

