[metadata]
name = "pinned-search"
version = "0.1.0"
description = "Evergreen hardened Pinned-Search - lightweight search engine"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/usr/local/bin/pinned-search"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened Pinned-Search - lightweight search engine"
"org.opencontainers.image.title" = "pinned-search"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.image.category" = "database"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

