[metadata]
name = "crawlergo"
version = "0.4.4"
description = "crawlergo container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/crawlergo"]

[ports]
expose = [0, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/Qianlitp/crawlergo/releases/download/v0.4.4"
"org.opencontainers.image.title" = "crawlergo"
"org.opencontainers.image.vendor" = "crawlergo"
"org.opencontainers.image.version" = "0.4.4"
"sovereign.base.image" = "scratch"
"sovereign.constraint.nonroot" = "true"
"sovereign.constraint.scratch" = "true"
"sovereign.health.type" = "exec"
"sovereign.hft.init-system" = "none"
"sovereign.hft.shutdown-timeout" = "3s"
"sovereign.hft.signal-handling" = "native"
"sovereign.hft.startup-timeout" = "3000ms"
"sovereign.image.tier" = "3"
"sovereign.metrics.native" = "ztunnel"

