[metadata]
tier = "standard"
name = "crawlergo"
version = "0.4.4"
description = "crawlergo container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/crawlergo"]

[ports]
expose = [0, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/Qianlitp/crawlergo/releases/download/v0.4.4"
"org.opencontainers.image.title" = "crawlergo"
"org.opencontainers.image.vendor" = "crawlergo"
"org.opencontainers.image.version" = "0.4.4"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "standard""evergreen.metrics.native" = "ztunnel"
