[metadata]
tier = "standard"
name = "tailscale"
version = "1.58.0"
description = "tailscale container image"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/tailscaled"]

[ports]
expose = ["41641/udp", 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/tailscale/tailscale"
"org.opencontainers.image.title" = "tailscale"
"org.opencontainers.image.vendor" = "Tailscale"
"org.opencontainers.image.version" = "1.58.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "networking"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
