[metadata]
name = "consul"
version = "1.18.1"
description = "Consul - service mesh, service discovery, and configuration"
vendor = "HashiCorp"
source = "https://github.com/hashicorp/consul"
license = "MPL-2.0"
tier = "critical"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://releases.hashicorp.com/consul/1.18.1/consul_1.18.1_linux_amd64.zip"

[runtime]
entrypoint = ["/consul"]

[ports]
expose = [8500, 9101]

[labels]
"org.opencontainers.image.title" = "consul"
"org.opencontainers.image.vendor" = "HashiCorp"
"org.opencontainers.image.version" = "1.18.1"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.cap-drop" = "ALL"
"evergreen.hft.cap-required" = "CAP_SYS_NICE"
"evergreen.hft.fips-required" = "true"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "5s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "5000ms"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

