[metadata]
name = "fluxcd-helm"
version = "2.8.6"
description = "Sovereign hardened fluxcd-helm - Helm controller for Flux"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/flux", "bootstrap", "helm-release"]

[ports]
expose = [9101]

[labels]
"org.opencontainers.image.description" = "Sovereign hardened fluxcd-helm - Helm controller for Flux"
"org.opencontainers.image.title" = "fluxcd-helm"
"org.opencontainers.image.vendor" = "Flux CD"
"org.opencontainers.image.version" = "2.8.6"
"sovereign.base.image" = "scratch"
"sovereign.constraint.nonroot" = "true"
"sovereign.constraint.scratch" = "true"
"sovereign.health.type" = "exec"
"sovereign.hft.shutdown-timeout" = "5s"
"sovereign.hft.signal-handling" = "native"
"sovereign.image.tier" = "3"
"sovereign.metrics.native" = "ztunnel"

