[metadata]
tier = "standard"
name = "wolfi-python"
version = "unknown"
description = "wolfi-python container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

