[metadata]
tier = "standard"
name = "filebeat"
version = "9.4.0"
description = "Evergreen hardened Filebeat - Elastic log file shipper"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/docker.elastic.co/beats/filebeat"
[runtime]
entrypoint = ["/opt/filebeat/filebeat"]

[ports]
expose = [5066, 9101]

[labels]
"org.opencontainers.image.description" = "Evergreen hardened Filebeat - Elastic log file shipper"
"org.opencontainers.image.title" = "filebeat"
"org.opencontainers.image.vendor" = "Elastic"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "observability"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
