[metadata]
name = "miniflux"
version = "2.2.19"
description = "Miniflux - minimalist RSS/Atom feed reader"
vendor = "Miniflux"
source = "https://github.com/miniflux/v2"
license = "Apache-2.0"
tier = "standard"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/miniflux/miniflux/releases/download/v2.2.19/miniflux-2.2.19-linux-amd64.tar.gz"

[runtime]
entrypoint = ["/miniflux"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.title" = "miniflux"
"org.opencontainers.image.vendor" = "Miniflux"
"org.opencontainers.image.version" = "${VERSION}"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "standard"
"evergreen.metrics.native" = "ztunnel"
