[metadata]
name = "fluent-bit"
version = "3.2.4"
description = "Fluent Bit - fast lightweight log processor and forwarder"
vendor = "Fluent"
source = "https://github.com/fluent/fluent-bit"
license = "Apache-2.0"
tier = "1"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "docker-image"
url = "fluent/fluent-bit:${VERSION}"

[runtime]
entrypoint = ["fluent-bit"]

[ports]
expose = [2020, 9101]

[labels]
"org.opencontainers.image.title" = "fluent-bit"
"org.opencontainers.image.vendor" = "Fluent"
"org.opencontainers.image.version" = "3.2.4"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

