[metadata]
tier = "standard"
name = "weaviate-python"
version = "4.10.0"
description = "weaviate-python container image"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["python3"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.source" = "https://github.com/weaviate/weaviate"
"org.opencontainers.image.title" = "weaviate-python"
"org.opencontainers.image.vendor" = "Weaviate"
"org.opencontainers.image.version" = "4.10.0"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "standard""evergreen.metrics.native" = "ztunnel"
