[metadata]
name = "prometheus-node-exporter"
version = "1.8.0"
description = "Node Exporter - hardware and OS metrics exporter for Prometheus"
vendor = "Prometheus"
source = "https://github.com/prometheus/node_exporter"
license = "Apache-2.0"
tier = "standard"

[build]
base = "scratch"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/prometheus-node-exporter/prometheus-node-exporter/releases/download/v1.8.0/prometheus-node-exporter-1.8.0-linux-amd64.tar.gz"

[runtime]
entrypoint = ["/node_exporter"]

[ports]
expose = [9100, 9101]

[labels]
"org.opencontainers.image.title" = "prometheus-node-exporter"
"org.opencontainers.image.vendor" = "Prometheus"
"org.opencontainers.image.version" = "1.8.0"
"evergreen.base.image" = "scratch"
"evergreen.constraint.nonroot" = "true"
"evergreen.constraint.scratch" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.connection-drain" = "false"
"evergreen.hft.cpu-pins" = "6-7"
"evergreen.hft.cpu-pins-mode" = "shared"
"evergreen.hft.deploy-strategy" = "standard-rolling"
"evergreen.hft.init-system" = "none"
"evergreen.hft.pre-stop-hook" = "false"
"evergreen.hft.sched-policy" = "SCHED_OTHER"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"

