name: Build and Push Images to GHCR

on:
  push:
    branches:
      - main
    tags:
      - '**/*v*'
  pull_request:
    branches:
      - main
    paths:
      - 'images/**'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [keycloak, traefik]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for changes in image directory
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'images/${{ matrix.image }}/**'

      - if: steps.changes.outputs.src == 'true'
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - if: steps.changes.outputs.src == 'true'
        name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.changes.outputs.src == 'true'
        name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag,pattern={{bslash}}v(.*)

      - if: steps.changes.outputs.src == 'true'
        name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./images/${{ matrix.image }}
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
