name: Build and Push Images to GHCR

on:
  push:
    branches:
      - main
    tags:
      - '**/*v*' # Trigger on tags like 'traefik/v3.5.2'
  pull_request:
    branches:
      - main
    paths:
      - 'images/**'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [keycloak, traefik]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for file changes (for PRs)
        id: changes
        if: github.event_name == 'pull_request'
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'images/${{ matrix.image }}/**'
      - name: Set up Docker Buildx
        if: (github.event_name == 'push' && github.ref_name == 'main') || (startsWith(github.ref, 'refs/tags/') && startsWith(github.ref_name, matrix.image)) || steps.changes.outputs.src == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: (github.event_name == 'push' && github.ref_name == 'main') || (startsWith(github.ref, 'refs/tags/') && startsWith(github.ref_name, matrix.image)) || steps.changes.outputs.src == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        if: (github.event_name == 'push' && github.ref_name == 'main') || (startsWith(github.ref, 'refs/tags/') && startsWith(github.ref_name, matrix.image)) || steps.changes.outputs.src == 'true'
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag,pattern={{prefix}}v(.*)
            type=semver,pattern={{prefix}}v(.*)

      - name: Build and push image
        if: (github.event_name == 'push' && github.ref_name == 'main') || (startsWith(github.ref, 'refs/tags/') && startsWith(github.ref_name, matrix.image)) || steps.changes.outputs.src == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./images/${{ matrix.image }}
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max