name: Lint & Format Check

on:
  pull_request:
    branches: [main]

jobs:
  # Check for consistent formatting with Prettier
  prettier-check:
    name: Prettier Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Prettier
        run: npm install --global prettier
      - name: Run Prettier Check
        run: prettier --check .

  # Check Dockerfiles with hadolint
  hadolint:
    name: Hadolint (Dockerfile Linter)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
          dockerfile: images/**/*.Dockerfile

  # Check Markdown files for style issues
  markdownlint:
    name: MarkdownLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: '**/*.md'

  # Check YAML files for syntax and style issues
  yamllint:
    name: YAMLLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_file_or_dir: '.'
          yamllint_config_filepath: '.yamllint.yml'
