[metadata]
tier = "standard"
name = "unbound-alpine"
version = "1.19.3"
description = "Unbound DNS resolver (alpine variant, built without Alpine)"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "65532:65532"
stopsignal = "SIGTERM"

[source]
type = "package-manager"

[runtime]
entrypoint = ["/usr/sbin/unbound"]
cmd = ["-d"]

[ports]
expose = [53, 9101]

[labels]
"org.opencontainers.image.description" = "Unbound DNS resolver (alpine variant, built without Alpine)"
"org.opencontainers.image.source" = "https://nlnetlabs.nl/projects/unbound/"
"org.opencontainers.image.title" = "unbound-alpine"
"org.opencontainers.image.vendor" = "NLnet Labs"
"org.opencontainers.image.version" = "1.19.3"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.base" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.hft.init-system" = "none"
"evergreen.hft.shutdown-timeout" = "3s"
"evergreen.hft.signal-handling" = "native"
"evergreen.hft.startup-timeout" = "3000ms"
"evergreen.image.category" = "networking"
"evergreen.image.status" = "functional"
"evergreen.image.tier" = "1"
"evergreen.metrics.native" = "ztunnel"
