apiVersion: v2
name: redis-exporter
description: "Redis exporter for Prometheus — Evergreen Image Registry hardened image"
type: application
version: 0.1.0
appVersion: "latest"
maintainers:
  - name: Wyatt Au
keywords:
  - redis-exporter
  - security
  - hardened
  - evergreen
home: https://github.com/WyattAu/EvergreenImageRegistry/tree/main/images/redis-exporter
sources:
  - https://github.com/WyattAu/EvergreenImageRegistry
