[metadata]
name = "jenkins"
version = "2.462.1"
description = "Jenkins - open source automation server for CI/CD"
vendor = "Jenkins"
source = "https://github.com/jenkinsci/jenkins"
license = "MIT"
tier = "critical"

[build]
base = "cgr.dev/chainguard/wolfi-base:latest"
user = "jenkins"
stopsignal = "SIGTERM"

[source]
type = "package-manager"
url = "https://github.com/jenkins/jenkins/releases/download/v2.462.1/jenkins-2.462.1-linux-amd64.tar.gz"

[runtime]
entrypoint = ["jenkins"]

[ports]
expose = [8080, 9101]

[labels]
"org.opencontainers.image.title" = "jenkins"
"org.opencontainers.image.vendor" = "Jenkins"
"org.opencontainers.image.version" = "2.462.1"
"evergreen.base.image" = "wolfi"
"evergreen.constraint.nonroot" = "true"
"evergreen.health.type" = "exec"
"evergreen.image.tier" = "2"
"evergreen.metrics.native" = "ztunnel"

